import {useEffect,useRef,useState} from 'react';
import {loadDraft,saveDraft} from '@/presentaciones-demo/storage';
import {dimensions,duration,totalDuration,timeline,locate,splitClip,moveClip,inspect,initialEdit,validate,type Edit,type Media} from './model';
import './editor.css';
import VideoPreview from '@/video-studio/VideoPreview';
import {MontagePreview} from './MontagePreview';
import {Filmstrip} from './Filmstrip';
import {listFusions} from '@/video-studio/fusion-cloud';
import {supabase} from '@/integrations/supabase/client';
const stamp=(n:number)=>`${Math.floor(n/60)}:${(n%60).toFixed(1).padStart(4,'0')}`;
export default function Editor(){
 const [edit,setEdit]=useState<Edit>(initialEdit),[media,setMedia]=useState<Media[]>([]),[selected,setSelected]=useState(''),[cursor,setCursor]=useState(0),[playing,setPlaying]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[result,setResult]=useState('');
 const [zoom,setZoom]=useState(75);
 const [panel,setPanel]=useState<'media'|'music'|'format'|'trim'|'speed'|'transition'|null>(null),[junction,setJunction]=useState('');
 const trimming=useRef<{id:string;edge:'start'|'end';x:number;original:Edit}|null>(null);
 const previewReady=useRef(false),clock=useRef(0),timelineScroll=useRef<HTMLDivElement>(null);
 const [past,setPast]=useState<Edit[]>([]),[future,setFuture]=useState<Edit[]>([]);
 const [generated,setGenerated]=useState<{id:string;name:string;url:string;duration?:number;createdAt?:string;created_at?:string}[]>([]);
 const audio=useRef<HTMLAudioElement>(null),abort=useRef<AbortController>(),urls=useRef(new Map<string,string>()),seekPending=useRef<number|null>(null),drag=useRef('');
 const length=totalDuration(edit.clips),position=locate(edit.clips,cursor),active=position?edit.clips[position.index]:null,clip=edit.clips.find(c=>c.id===selected),asset=active?media.find(m=>m.id===active.mediaId):null;
 const url=(m:Media|null|undefined)=>{if(!m)return '';if(!urls.current.has(m.id))urls.current.set(m.id,URL.createObjectURL(m.file));return urls.current.get(m.id)!;};
 const musicSource=url(edit.music);
 const rows=timeline(edit.clips);
 const trackWidth=Math.max(600,(length+2)*zoom);
 const stop=()=>{setPlaying(false);audio.current?.pause();};
 const seek=(n:number)=>{stop();seekPending.current=n;setCursor(n);};
 const change=(next:Edit)=>{stop();setResult('');setPast(p=>[...p.slice(-29),edit]);setFuture([]);setEdit(next);setCursor(0);seekPending.current=0;setDirty(true);};
 useEffect(()=>{const cache=urls.current;return()=>{abort.current?.abort();cache.forEach(URL.revokeObjectURL);};},[]);
 useEffect(()=>{if(!result)return;return()=>URL.revokeObjectURL(result);},[result]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty,busy]);
 useEffect(()=>{loadDraft<{edit:Edit;media:Media[]}>('video-editor-v1').then(d=>{if(d){validate(d.edit,d.media);setMedia(d.media);setEdit(d.edit);setSelected(d.edit.clips[0]?.id||'');setMessage('Montaje recuperado de este equipo.');}}).catch(()=>setMessage('No se pudo recuperar el montaje guardado.'));},[]);

 useEffect(()=>{const a=audio.current;if(!a)return;a.volume=edit.volume;const t=edit.musicStart+cursor;if(edit.music&&t<edit.music.duration){if(Math.abs(a.currentTime-t)>.2)a.currentTime=t;if(playing&&a.paused)a.play().catch(()=>{});if(!playing)a.pause();}else a.pause();},[cursor,playing,musicSource,edit.volume]);
 const importFiles=async(files:FileList|File[]|null,kind:'video'|'audio')=>{if(!files||files.length===0||busy)return;stop();setBusy(true);try{const additions:Media[]=[];for(const file of Array.from(files)){if(file.size>100*1024*1024)throw Error('Cada archivo admite hasta 100 MB.');if(media.reduce((n,m)=>n+m.file.size,0)+additions.reduce((n,m)=>n+m.file.size,0)+file.size>250*1024*1024)throw Error('El montaje admite hasta 250 MB de archivos.');additions.push({id:crypto.randomUUID(),name:file.name,file,duration:await inspect(file,kind)});}if(kind==='audio')change({...edit,music:additions[0],musicStart:0});else{const assets=[...media,...additions];const clips=additions.map(m=>({id:crypto.randomUUID(),mediaId:m.id,start:0,end:m.duration,speed:1}));const next={...edit,clips:[...edit.clips,...clips]};validate(next,assets);setMedia(assets);change(next);setSelected(clips[0]?.id||selected);setPanel(null);}setMessage(kind==='audio'?'Música lista.':'Videos añadidos a la línea de tiempo.');}catch(e){setMessage(String((e as Error).message));}finally{setBusy(false);}};
 const loadGenerated=async()=>{setBusy(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Inicia sesión en Renders para acceder a tus videos generados.');const {data,error}=await supabase.functions.invoke('video-clips',{body:{action:'list'}});if(error)throw Error('No se pudieron cargar tus tomas. Puedes descargarlas desde Video e importarlas aquí.');const jobs=(data?.jobs||[]).filter((j:{state:string;url:string|null})=>j.state==='completed'&&j.url);const fusions=await listFusions();setGenerated([...fusions,...jobs]);setMessage(jobs.length||fusions.length?'Selecciona una toma para traerla al editor.':'Todavía no hay videos terminados en tu cuenta.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 const importGenerated=async(j:{id:string;name:string;url:string},target?:string)=>{if(busy)return;setBusy(true);setMessage('Preparando toma para la línea de tiempo…');try{const existing=media.find(m=>m.id===j.id);if(existing){add(existing,target);return;}const response=await fetch(j.url,{signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error('No se pudo descargar. Actualiza tus tomas e inténtalo otra vez.');const file=await response.blob();if(file.size>100*1024*1024||media.reduce((n,m)=>n+m.file.size,0)+file.size>250*1024*1024)throw Error('La biblioteca admite 100 MB por video y 250 MB en total.');const m={id:j.id,name:j.name||'Mi toma',file,duration:await inspect(file,'video')};if(add(m,target,[...media,m]))setMedia(ms=>[...ms,m]);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 const add=(m:Media,target?:string,assets:Media[]=media)=>{const c={id:crypto.randomUUID(),mediaId:m.id,start:0,end:m.duration,speed:1};const items=[...edit.clips];const at=target?items.findIndex(x=>x.id===target):-1;items.splice(at<0?items.length:at,0,c);const next={...edit,clips:items};try{validate(next,assets);change(next);setSelected(c.id);setPanel(null);setMessage('Toma añadida a la línea de tiempo.');return true;}catch(e){setMessage((e as Error).message);return false;}};
 const update=(values:Partial<NonNullable<typeof clip>>)=>{if(!clip)return;const next={...edit,clips:edit.clips.map(c=>c.id===clip.id?{...c,...values}:c)};try{validate(next,media);change(next);}catch(e){setMessage((e as Error).message);}};
 const exportVideo=async()=>{stop();setBusy(true);abort.current=new AbortController();try{const {exportMontage}=await import('./export');const blob=await exportMontage(edit,media,setMessage,abort.current.signal);setResult(URL.createObjectURL(blob));setMessage('Tu MP4 está listo para descargar.');}catch(e){setMessage(abort.current.signal.aborted?'Exportación cancelada.':(e as Error).message);}finally{abort.current=undefined;setBusy(false);}};
 const split=()=>{try{if(!clip||active?.id!==clip.id)throw Error('Selecciona la toma y sitúa el cursor donde quieres cortar.');const pieces=splitClip(clip,position!.local);const next={...edit,clips:edit.clips.flatMap(c=>c.id===clip.id?pieces:[c])};validate(next,media);change(next);setSelected(pieces[1].id);setCursor(cursor);setMessage('Toma dividida. Cada fragmento se puede editar por separado.');}catch(e){setMessage((e as Error).message);}};
 const trimStart=(e:React.PointerEvent,id:string,edge:'start'|'end')=>{e.preventDefault();e.stopPropagation();stop();setSelected(id);trimming.current={id,edge,x:e.clientX,original:edit};e.currentTarget.setPointerCapture(e.pointerId);};
 const trimMove=(e:React.PointerEvent)=>{const t=trimming.current;if(!t)return;const c=t.original.clips.find(c=>c.id===t.id)!;const max=media.find(m=>m.id===c.mediaId)!.duration;const delta=(e.clientX-t.x)/zoom*c.speed;const value=t.edge==='start'?Math.max(0,Math.min(c.end-.1,c.start+delta)):Math.min(max,Math.max(c.start+.1,c.end+delta));const next={...t.original,clips:t.original.clips.map(x=>x.id===c.id?{...x,[t.edge]:Math.round(value*30)/30}:x)};try{validate(next,media);setEdit(next);setResult('');setCursor(0);}catch{}};
 const trimEnd=()=>{const t=trimming.current;if(!t)return;setPast(p=>[...p.slice(-29),t.original]);setFuture([]);setDirty(true);trimming.current=null;};
 const duplicate=()=>{if(!clip)return;const copy={...clip,id:crypto.randomUUID()};const clips=[...edit.clips];clips.splice(clips.indexOf(clip)+1,0,copy);try{validate({...edit,clips},media);change({...edit,clips});setSelected(copy.id);}catch(e){setMessage((e as Error).message);}};
 const drop=(e:React.DragEvent,target?:string)=>{e.preventDefault();e.stopPropagation();if(busy)return;if(e.dataTransfer.files.length){void importFiles(e.dataTransfer.files,'video');return;}const job=generated.find(j=>`generated:${j.id}`===drag.current);if(job){drag.current='';void importGenerated(job,target);return;}const m=media.find(m=>`media:${m.id}`===drag.current);if(m)add(m,target);else if(drag.current){const targetId=target||edit.clips.at(-1)?.id;if(targetId)change({...edit,clips:moveClip(edit.clips,drag.current,targetId)});}drag.current='';};
 useEffect(()=>{if(!playing)return;clock.current=performance.now();let frame:number;const advance=(now:number)=>{const delta=(now-clock.current)/1000;clock.current=now;if(previewReady.current)setCursor(t=>Math.min(length,t+delta));frame=requestAnimationFrame(advance);};frame=requestAnimationFrame(advance);return()=>cancelAnimationFrame(frame);},[playing,length]);
 useEffect(()=>{if(playing&&cursor>=length)stop();},[cursor,length,playing]);
 return <main className="ve"><header><div><span className="ve-eyebrow">DEL CLIP A LA HISTORIA</span><h1>Mi montaje</h1><p>Edita tus tomas, encuentra tu ritmo.</p></div><div className="ve-actions"><button disabled={busy||!edit.clips.length} onClick={async()=>{try{await saveDraft({edit,media},'video-editor-v1');setDirty(false);setMessage('Guardado en este navegador y equipo.');}catch{setMessage('No hay espacio para guardar. Exporta tu montaje antes de salir.');}}}>Guardar en este equipo{dirty?' •':''}</button><button className="ve-primary" disabled={busy||!edit.clips.length} onClick={exportVideo}>Exportar MP4</button></div></header>
 <div role="status" className="ve-status">{message||'Primera versión · Hasta 2 minutos · La edición no consume créditos de generación.'}{busy&&abort.current&&!abort.current.signal.aborted&&<button onClick={()=>abort.current?.abort()}>Cancelar exportación</button>}{result&&<a download="arquirender-montaje.mp4" href={result}>Descargar MP4</a>}</div>
 <fieldset disabled={busy} className="ve-work"><aside data-panel={panel} hidden={!panel||!['media','music','format'].includes(panel)} className="ve-tools" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void importFiles(e.dataTransfer.files,'video');}}><button className="ve-close" aria-label="Cerrar panel" onClick={()=>setPanel(null)}>×</button><div className="ve-media-panel"><h2>Tus videos</h2><label className="ve-upload">+ Subir videos<input aria-label="Subir videos" type="file" multiple accept="video/mp4,video/webm,video/quicktime" onChange={e=>{importFiles(e.target.files,'video');e.target.value='';}}/></label><p className="ve-hint">MP4 o WebM · 100 MB por archivo. Importa desde tu equipo o trae tus tomas de ArquiRender.</p><button onClick={loadGenerated}>Traer mis videos generados</button>{generated.length>0&&<div className="ve-generated">{generated.map(j=><button className="ve-saved-take" key={j.id} draggable={!busy} onDragStart={e=>{drag.current=`generated:${j.id}`;e.dataTransfer.setData('text/plain',drag.current);e.dataTransfer.effectAllowed='copy';}} onDragEnd={()=>{drag.current='';}} onClick={()=>importGenerated(j)}><VideoPreview src={j.url} name={j.name||'Mi toma'} thumbnail/><span><strong>{j.name||'Mi toma'}</strong><small>{j.duration?`${j.duration} s · `:''}{(j.createdAt||j.created_at)?new Date((j.createdAt||j.created_at)!).toLocaleString('es',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):''}</small><small className="ve-import-label">+ Añadir al montaje</small></span></button>)}</div>}<div className="ve-library">{media.map(m=><button key={m.id} draggable={!busy} onDragStart={e=>{drag.current=`media:${m.id}`;e.dataTransfer.setData('text/plain',drag.current);}} onClick={()=>add(m)}><video src={url(m)} preload="metadata" muted onLoadedMetadata={e=>{e.currentTarget.currentTime=Math.min(.1,m.duration/2);}}/><span>{m.name}<small>{stamp(m.duration)} · + Añadir</small></span></button>)}</div>
 </div><div className="ve-music-panel"><h2>Música</h2><label className="ve-upload">{edit.music?'Cambiar música':'+ Añadir música'}<input aria-label="Añadir música" type="file" accept="audio/*" onChange={e=>{importFiles(e.target.files,'audio');e.target.value='';}}/></label><p className="ve-hint">El audio original queda silenciado. La música acompaña todo el montaje; si termina antes, el resto queda en silencio.</p>{edit.music&&<><p>{edit.music.name}</p><label>Inicio de la música (segundos)<input aria-label="Inicio de la música" type="number" min="0" max={edit.music.duration-.1} step=".1" value={edit.musicStart} onChange={e=>change({...edit,musicStart:Math.max(0,Math.min(edit.music!.duration-.1,Number(e.target.value)))})}/></label><label>Volumen · {Math.round(edit.volume*100)}%<input aria-label="Volumen" type="range" min="0" max="1" step=".05" value={edit.volume} onChange={e=>change({...edit,volume:Number(e.target.value)})}/></label><button onClick={()=>change({...edit,music:null})}>Quitar música</button></>}
 </div><div className="ve-format-panel"><h2>Formato final</h2><label>Proporción<select value={edit.format} onChange={e=>change({...edit,format:e.target.value as Edit['format']})}><option>16:9</option><option>9:16</option><option>1:1</option></select></label><label>Resolución<select value={edit.resolution} onChange={e=>change({...edit,resolution:Number(e.target.value) as 720|1080})}><option value="720">720p · más rápido</option><option value="1080">1080p · más detalle</option></select></label><p className="ve-hint">Conservamos la imagen completa con márgenes negros cuando hace falta. Mantén esta pestaña abierta durante la exportación.</p></div></aside>
 <section className="ve-stage"><div className="ve-player" style={{aspectRatio:edit.format.replace(':','/'),maxWidth:`calc(28vh * ${edit.format==='16:9'?16/9:edit.format==='9:16'?9/16:1})`}}>{active?<MontagePreview width={dimensions(edit)[0]} height={dimensions(edit)[1]} clips={edit.clips} cursor={cursor} playing={playing} source={id=>url(media.find(m=>m.id===id))} onReady={ready=>{previewReady.current=ready;}} onError={()=>{setPlaying(false);setMessage('No se pudo reproducir una toma. Revisa el archivo.');}}/>:<div><h2>Tu historia empieza aquí</h2><p>Importa una toma para empezar tu montaje.</p><button onClick={()=>setPanel('media')}>+ Importar videos</button></div>}</div><audio ref={audio} src={musicSource||undefined}/><div className="ve-transport"><button disabled={!active} onClick={()=>{if(playing)stop();else{if(cursor>=length){seek(0);setPlaying(true);}else{setPlaying(true);}}}}>{playing?'Pausar':'Reproducir'}</button><span>{stamp(cursor)} / {stamp(length)}</span></div><input className="ve-scrub" aria-label="Posición del montaje" type="range" min="0" max={length||1} step=".033333" value={cursor} onChange={e=>seek(Number(e.target.value))}/>
 <div className="ve-timeline-head"><h2>Línea de tiempo</h2><div><button disabled={!past.length} onClick={()=>{stop();setResult('');setFuture(f=>[edit,...f]);setEdit(past[past.length-1]);setPast(p=>p.slice(0,-1));setCursor(0);setDirty(true);}}>Deshacer</button><button disabled={!future.length} onClick={()=>{stop();setResult('');setPast(p=>[...p,edit]);setEdit(future[0]);setFuture(f=>f.slice(1));setCursor(0);setDirty(true);}}>Rehacer</button><label>Zoom<input aria-label="Zoom de la línea de tiempo" type="range" min="20" max="140" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label></div></div>
 <p className="ve-hint ve-timeline-help">Selecciona una toma · Arrastra sus bordes para recortar · Pulsa + entre tomas para añadir una fusión</p>
 <div className="ve-timeline-scroll" ref={timelineScroll} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e)}><div className="ve-track" style={{width:trackWidth}}>
 <div className="ve-ruler" aria-label="Regla de segundos" onClick={e=>seek(Math.min(length,Math.max(0,(e.clientX-e.currentTarget.getBoundingClientRect().left)/zoom)))}>{Array.from({length:Math.ceil(trackWidth/zoom)+1},(_,i)=><span key={i} style={{left:i*zoom}}>{stamp(i)}</span>)}</div>
 <div className="ve-video-lane">{rows.map(({clip:c,start},i)=><div className="ve-clip-shell" style={{left:(start+(i?rows[i-1].overlap/2:0))*zoom,width:(duration(c)-(i?rows[i-1].overlap/2:0)-rows[i].overlap/2)*zoom}} key={c.id} data-selected={selected===c.id}><button className="ve-timeline-clip" draggable={!busy} aria-label={`Toma ${i+1}: ${media.find(m=>m.id===c.mediaId)?.name}`} aria-pressed={selected===c.id} onDragStart={e=>{drag.current=c.id;e.dataTransfer.setData('text/plain',c.id);}} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,c.id)} onClick={()=>{setSelected(c.id);seek(start);setPanel(null);}}><strong>{i+1} · {media.find(m=>m.id===c.mediaId)?.name}</strong><Filmstrip src={url(media.find(m=>m.id===c.mediaId))} start={c.start} end={c.end}/><small>{stamp(duration(c))} · {c.speed}×</small></button>{selected===c.id&&(['start','end'] as const).map(edge=><span key={edge} role="slider" tabIndex={0} aria-label={edge==='start'?'Recortar inicio':'Recortar final'} aria-valuenow={c[edge]} aria-valuemin={edge==='start'?0:c.start+.1} aria-valuemax={edge==='start'?c.end-.1:media.find(m=>m.id===c.mediaId)?.duration} className={`ve-trim ve-trim-${edge}`} onPointerDown={e=>trimStart(e,c.id,edge)} onPointerMove={trimMove} onPointerUp={trimEnd} onPointerCancel={trimEnd} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();update({[edge]:c[edge]+(e.key==='ArrowRight'?.1:-.1)});}}}>Ⅱ</span>)}</div>)}{!rows.length&&<button className="ve-drop-hint" onClick={()=>setPanel('media')}>+ Importar o arrastrar videos aquí</button>}</div>
 <div className="ve-transition-lane">{rows.slice(0,-1).map((r,i)=><button key={r.clip.id} className="ve-junction" style={{left:Math.max(0,(r.end-r.overlap)*zoom-(r.overlap?0:14)),width:r.overlap?Math.max(28,r.overlap*zoom):28}} aria-label={`Transición después de toma ${i+1}`} title={r.overlap?`Fusión ${r.overlap.toFixed(1)} s`:'Añadir transición'} onClick={()=>{setJunction(r.clip.id);setPanel('transition');}}>{r.overlap?`⋈ ${r.overlap.toFixed(1)} s`:'+'}</button>)}<button className="ve-add-end" style={{left:length*zoom+12}} aria-label="Añadir otra toma" onClick={()=>setPanel('media')}>+</button></div>
 <div className="ve-audio-lane">{edit.music?<div style={{width:Math.min(length,edit.music.duration-edit.musicStart)*zoom}}>♫ {edit.music.name}</div>:<span>♫ Añade música desde la biblioteca</span>}</div>
 <div className="ve-playhead" style={{left:Math.min(cursor,length)*zoom}}><span/></div>
 </div></div>

 <nav className="ve-bottom-tools" aria-label="Herramientas de edición"><button onClick={()=>setPanel('media')}><b>＋</b>Videos</button><button onClick={()=>setPanel('music')}><b>♫</b>Audio</button>{clip&&<><button onClick={split}><b>✂</b>Dividir</button><button onClick={()=>setPanel('trim')}><b>↔</b>Recortar</button><button onClick={()=>setPanel('speed')}><b>◷</b>Velocidad</button><button onClick={duplicate}><b>▣</b>Duplicar</button>{[-1,1].map(d=><button key={d} disabled={!edit.clips[edit.clips.indexOf(clip)+d]} onClick={()=>change({...edit,clips:moveClip(edit.clips,clip.id,edit.clips[edit.clips.indexOf(clip)+d].id)})}><b>{d===-1?'←':'→'}</b>{d===-1?'Antes':'Después'}</button>)}<button onClick={()=>{change({...edit,clips:edit.clips.filter(c=>c.id!==clip.id)});setSelected('');setPanel(null);}}><b>×</b>Eliminar</button></>}<button onClick={()=>setPanel('format')}><b>▭</b>Formato</button></nav>
 {clip&&(panel==='trim'||panel==='speed')&&<div className="ve-clip-controls ve-sheet"><button className="ve-close" aria-label="Cerrar ajustes" onClick={()=>setPanel(null)}>✓</button><h3>{panel==='speed'?'Velocidad':'Recortar toma'} · {media.find(m=>m.id===clip.mediaId)?.name}</h3>{panel==='trim'?<><p className="ve-hint">Arrastra los extremos de la toma o ajusta los segundos.</p><div className="ve-fields"><label>Desde (s)<input aria-label="Desde" type="number" step=".1" min="0" max={clip.end-.1} value={clip.start} onChange={e=>update({start:Number(e.target.value)})}/></label><label>Hasta (s)<input aria-label="Hasta" type="number" step=".1" min={clip.start+.1} max={media.find(m=>m.id===clip.mediaId)?.duration} value={clip.end} onChange={e=>update({end:Number(e.target.value)})}/></label></div></>:<><p className="ve-hint">Duración de esta toma: {stamp(duration(clip))}</p><div className="ve-speed-options">{[.25,.5,1,1.5,2,4].map(v=><button key={v} aria-pressed={clip.speed===v} onClick={()=>update({speed:v})}>{v}×</button>)}</div></>}</div>}
 {panel==='transition'&&<div className="ve-sheet ve-clip-controls"><button className="ve-close" aria-label="Cerrar transiciones" onClick={()=>setPanel(null)}>✓</button><h3>Transición entre tomas</h3><p className="ve-hint">Las dos tomas se mezclan durante la zona marcada: al centro, cada una aporta el 50 %.</p><div className="ve-speed-options">{(['linear','smooth'] as const).map(kind=><button key={kind} aria-pressed={(edit.clips.find(c=>c.id===junction)?.transitionKind||'linear')===kind} onClick={()=>change({...edit,clips:edit.clips.map(c=>c.id===junction?{...c,transitionKind:kind,transition:c.transition||.5}:c)})}>{kind==='linear'?'Fundido cruzado':'Fundido suave'}</button>)}</div><div className="ve-speed-options">{[0,.5,1,1.5,2].map(v=><button key={v} aria-pressed={(edit.clips.find(c=>c.id===junction)?.transition||0)===v} onClick={()=>change({...edit,clips:edit.clips.map(c=>c.id===junction?{...c,transition:v}:c)})}>{v?`Fusión ${v} s`:'Sin transición'}</button>)}</div><p className="ve-hint">En tomas cortas, la fusión se ajusta a la mitad de la toma más breve.</p><button onClick={()=>{const chosen=edit.clips.find(c=>c.id===junction);const v=chosen?.transition||0;change({...edit,clips:edit.clips.map(c=>({...c,transition:v,transitionKind:chosen?.transitionKind}))});}}>Aplicar a todas las uniones</button></div>}
 </section></fieldset></main>;
}
