import {useEffect,useRef,useState} from 'react';
import {loadDraft,saveDraft} from '@/presentaciones-demo/storage';
import {duration,totalDuration,timeline,locate,splitClip,moveClip,inspect,initialEdit,validate,type Edit,type Media} from './model';
import './editor.css';
import {listFusions} from '@/video-studio/fusion-cloud';
import {supabase} from '@/integrations/supabase/client';
const stamp=(n:number)=>`${Math.floor(n/60)}:${(n%60).toFixed(1).padStart(4,'0')}`;
export default function Editor(){
 const [edit,setEdit]=useState<Edit>(initialEdit),[media,setMedia]=useState<Media[]>([]),[selected,setSelected]=useState(''),[cursor,setCursor]=useState(0),[playing,setPlaying]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[result,setResult]=useState('');
 const [zoom,setZoom]=useState(60);
 const overlay=useRef<HTMLVideoElement>(null),clock=useRef(0),timelineScroll=useRef<HTMLDivElement>(null);
 const [past,setPast]=useState<Edit[]>([]),[future,setFuture]=useState<Edit[]>([]);
 const [generated,setGenerated]=useState<{id:string;name:string;url:string}[]>([]);
 const video=useRef<HTMLVideoElement>(null),audio=useRef<HTMLAudioElement>(null),abort=useRef<AbortController>(),urls=useRef(new Map<string,string>()),seekPending=useRef<number|null>(null),drag=useRef('');
 const length=totalDuration(edit.clips),position=locate(edit.clips,cursor),active=position?edit.clips[position.index]:null,clip=edit.clips.find(c=>c.id===selected),asset=active?media.find(m=>m.id===active.mediaId):null;
 const url=(m:Media|null|undefined)=>{if(!m)return '';if(!urls.current.has(m.id))urls.current.set(m.id,URL.createObjectURL(m.file));return urls.current.get(m.id)!;};
 const source=url(asset),musicSource=url(edit.music);
 const rows=timeline(edit.clips),previous=position&&position.index>0?rows[position.index-1]:null;
 const fading=previous&&previous.end>cursor?previous:null;
 const overlaySource=url(fading?media.find(m=>m.id===fading.clip.mediaId):null);
 const trackWidth=Math.max(600,(length+2)*zoom);
 const syncVideo=(v:HTMLVideoElement|null,c:typeof active,t:number)=>{if(!v||!c)return;const target=c.start+t*c.speed;v.playbackRate=c.speed;if(Number.isFinite(target)&&Math.abs(v.currentTime-target)>(playing?.15:.015))v.currentTime=target;if(playing&&v.paused)v.play().catch(()=>setPlaying(false));if(!playing)v.pause();};
 const stop=()=>{setPlaying(false);video.current?.pause();audio.current?.pause();overlay.current?.pause();};
 const seek=(n:number)=>{stop();seekPending.current=n;setCursor(n);const p=locate(edit.clips,n);if(p&&video.current&&edit.clips[p.index].id===active?.id)video.current.currentTime=edit.clips[p.index].start+p.local*edit.clips[p.index].speed;};
 const change=(next:Edit)=>{stop();setResult('');setPast(p=>[...p.slice(-29),edit]);setFuture([]);setEdit(next);setCursor(0);seekPending.current=0;setDirty(true);};
 useEffect(()=>{const cache=urls.current;return()=>{abort.current?.abort();cache.forEach(URL.revokeObjectURL);};},[]);
 useEffect(()=>{if(!result)return;return()=>URL.revokeObjectURL(result);},[result]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty,busy]);
 useEffect(()=>{loadDraft<{edit:Edit;media:Media[]}>('video-editor-v1').then(d=>{if(d){validate(d.edit,d.media);setMedia(d.media);setEdit(d.edit);setSelected(d.edit.clips[0]?.id||'');setMessage('Montaje recuperado de este equipo.');}}).catch(()=>setMessage('No se pudo recuperar el montaje guardado.'));},[]);
 useEffect(()=>{syncVideo(video.current,active,position?.local||0);if(fading)syncVideo(overlay.current,fading.clip,cursor-fading.start);},[cursor,playing,source,overlaySource,edit]);
 useEffect(()=>{const a=audio.current;if(!a)return;a.volume=edit.volume;const t=edit.musicStart+cursor;if(edit.music&&t<edit.music.duration){if(Math.abs(a.currentTime-t)>.2)a.currentTime=t;if(playing&&a.paused)a.play().catch(()=>{});if(!playing)a.pause();}else a.pause();},[cursor,playing,musicSource,edit.volume]);
 const importFiles=async(files:FileList|File[]|null,kind:'video'|'audio')=>{if(!files)return;stop();setBusy(true);try{const additions:Media[]=[];for(const file of Array.from(files)){if(file.size>100*1024*1024)throw Error('Cada archivo admite hasta 100 MB.');if(media.reduce((n,m)=>n+m.file.size,0)+additions.reduce((n,m)=>n+m.file.size,0)+file.size>250*1024*1024)throw Error('El montaje admite hasta 250 MB de archivos.');additions.push({id:crypto.randomUUID(),name:file.name,file,duration:await inspect(file,kind)});}if(kind==='audio')change({...edit,music:additions[0],musicStart:0});else{setMedia(m=>[...m,...additions]);setDirty(true);}setMessage(kind==='audio'?'Música lista.':'Videos listos. Arrástralos a la pista o pulsa + para añadirlos.');}catch(e){setMessage(String((e as Error).message));}finally{setBusy(false);}};
 const loadGenerated=async()=>{setBusy(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Inicia sesión en Renders para acceder a tus videos generados.');const {data,error}=await supabase.functions.invoke('video-clips',{body:{action:'list'}});if(error)throw Error('No se pudieron cargar tus tomas. Puedes descargarlas desde Video e importarlas aquí.');const jobs=(data?.jobs||[]).filter((j:{state:string;url:string|null})=>j.state==='completed'&&j.url);const fusions=await listFusions();setGenerated([...fusions,...jobs]);setMessage(jobs.length||fusions.length?'Selecciona una toma para traerla al editor.':'Todavía no hay videos terminados en tu cuenta.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 const importGenerated=async(j:{id:string;name:string;url:string})=>{setBusy(true);try{if(media.some(m=>m.id===j.id)){setMessage('Esta toma ya está en tu biblioteca.');return;}const response=await fetch(j.url,{signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error('No se pudo descargar. Actualiza tus tomas e inténtalo otra vez.');const file=await response.blob();if(file.size>100*1024*1024||media.reduce((n,m)=>n+m.file.size,0)+file.size>250*1024*1024)throw Error('La biblioteca admite 100 MB por video y 250 MB en total.');const m={id:j.id,name:j.name||'Mi toma',file,duration:await inspect(file,'video')};setMedia(ms=>[...ms,m]);setDirty(true);setMessage('Toma importada. Pulsa + para añadirla al montaje.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 const add=(m:Media,target?:string)=>{const c={id:crypto.randomUUID(),mediaId:m.id,start:0,end:m.duration,speed:1};const items=[...edit.clips];const at=target?items.findIndex(x=>x.id===target):-1;items.splice(at<0?items.length:at,0,c);const next={...edit,clips:items};try{validate(next,media);change(next);setSelected(c.id);}catch(e){setMessage((e as Error).message);}};
 const update=(values:Partial<NonNullable<typeof clip>>)=>{if(!clip)return;const next={...edit,clips:edit.clips.map(c=>c.id===clip.id?{...c,...values}:c)};try{validate(next,media);change(next);}catch(e){setMessage((e as Error).message);}};
 const exportVideo=async()=>{stop();setBusy(true);abort.current=new AbortController();try{const {exportMontage}=await import('./export');const blob=await exportMontage(edit,media,setMessage,abort.current.signal);setResult(URL.createObjectURL(blob));setMessage('Tu MP4 está listo para descargar.');}catch(e){setMessage(abort.current.signal.aborted?'Exportación cancelada.':(e as Error).message);}finally{abort.current=undefined;setBusy(false);}};
 const split=()=>{try{if(!clip||active?.id!==clip.id)throw Error('Selecciona la toma y sitúa el cursor donde quieres cortar.');const pieces=splitClip(clip,position!.local);const next={...edit,clips:edit.clips.flatMap(c=>c.id===clip.id?pieces:[c])};validate(next,media);change(next);setSelected(pieces[1].id);setMessage('Toma dividida. Cada fragmento se puede editar por separado.');}catch(e){setMessage((e as Error).message);}};
 const drop=(e:React.DragEvent,target?:string)=>{e.preventDefault();e.stopPropagation();if(busy)return;if(e.dataTransfer.files.length){void importFiles(e.dataTransfer.files,'video');return;}const m=media.find(m=>`media:${m.id}`===drag.current);if(m)add(m,target);else if(drag.current){const targetId=target||edit.clips.at(-1)?.id;if(targetId)change({...edit,clips:moveClip(edit.clips,drag.current,targetId)});}drag.current='';};
 useEffect(()=>{if(!playing)return;clock.current=performance.now();let frame:number;const advance=(now:number)=>{const delta=(now-clock.current)/1000;clock.current=now;setCursor(t=>Math.min(length,t+delta));frame=requestAnimationFrame(advance);};frame=requestAnimationFrame(advance);return()=>cancelAnimationFrame(frame);},[playing,length]);
 useEffect(()=>{if(playing&&cursor>=length)stop();},[cursor,length,playing]);
 return <main className="ve"><header><div><span className="ve-eyebrow">DEL CLIP A LA HISTORIA</span><h1>Editor de video</h1><p>Ordena tus tomas. Encuentra el ritmo.</p></div><div className="ve-actions"><button disabled={busy||!edit.clips.length} onClick={async()=>{try{await saveDraft({edit,media},'video-editor-v1');setDirty(false);setMessage('Guardado en este navegador y equipo.');}catch{setMessage('No hay espacio para guardar. Exporta tu montaje antes de salir.');}}}>Guardar en este equipo{dirty?' •':''}</button><button className="ve-primary" disabled={busy||!edit.clips.length} onClick={exportVideo}>Exportar MP4</button></div></header>
 <div role="status" className="ve-status">{message||'Primera versión · Hasta 2 minutos · La edición no consume créditos de generación.'}{busy&&abort.current&&!abort.current.signal.aborted&&<button onClick={()=>abort.current?.abort()}>Cancelar exportación</button>}{result&&<a download="arquirender-montaje.mp4" href={result}>Descargar MP4</a>}</div>
 <fieldset disabled={busy} className="ve-work"><aside className="ve-tools" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void importFiles(e.dataTransfer.files,'video');}}><h2>01 · Tus videos</h2><label className="ve-upload">+ Subir videos<input aria-label="Subir videos" type="file" multiple accept="video/mp4,video/webm,video/quicktime" onChange={e=>{importFiles(e.target.files,'video');e.target.value='';}}/></label><p className="ve-hint">MP4 o WebM · 100 MB por archivo. Importa desde tu equipo o trae tus tomas de ArquiRender.</p><button onClick={loadGenerated}>Traer mis videos generados</button>{generated.length>0&&<div className="ve-generated">{generated.map(j=><button key={j.id} onClick={()=>importGenerated(j)}>↓ {j.name||'Mi toma'}</button>)}</div>}<div className="ve-library">{media.map(m=><button key={m.id} draggable={!busy} onDragStart={e=>{drag.current=`media:${m.id}`;e.dataTransfer.setData('text/plain',drag.current);}} onClick={()=>add(m)}><video src={url(m)} preload="metadata" muted onLoadedMetadata={e=>{e.currentTarget.currentTime=Math.min(.1,m.duration/2);}}/><span>{m.name}<small>{stamp(m.duration)} · + Añadir</small></span></button>)}</div>
 <h2>02 · Música</h2><label className="ve-upload">{edit.music?'Cambiar música':'+ Añadir música'}<input aria-label="Añadir música" type="file" accept="audio/*" onChange={e=>{importFiles(e.target.files,'audio');e.target.value='';}}/></label><p className="ve-hint">El audio original queda silenciado. La música acompaña todo el montaje; si termina antes, el resto queda en silencio.</p>{edit.music&&<><p>{edit.music.name}</p><label>Inicio de la música (segundos)<input aria-label="Inicio de la música" type="number" min="0" max={edit.music.duration-.1} step=".1" value={edit.musicStart} onChange={e=>change({...edit,musicStart:Math.max(0,Math.min(edit.music!.duration-.1,Number(e.target.value)))})}/></label><label>Volumen · {Math.round(edit.volume*100)}%<input aria-label="Volumen" type="range" min="0" max="1" step=".05" value={edit.volume} onChange={e=>change({...edit,volume:Number(e.target.value)})}/></label><button onClick={()=>change({...edit,music:null})}>Quitar música</button></>}
 <h2>03 · Formato final</h2><label>Proporción<select value={edit.format} onChange={e=>change({...edit,format:e.target.value as Edit['format']})}><option>16:9</option><option>9:16</option><option>1:1</option></select></label><label>Resolución<select value={edit.resolution} onChange={e=>change({...edit,resolution:Number(e.target.value) as 720|1080})}><option value="720">720p · más rápido</option><option value="1080">1080p · más detalle</option></select></label><p className="ve-hint">Conservamos la imagen completa con márgenes negros cuando hace falta. Mantén esta pestaña abierta durante la exportación.</p></aside>
 <section className="ve-stage"><div className="ve-player" style={{aspectRatio:edit.format.replace(':','/'),maxWidth:`calc(34vh * ${edit.format==='16:9'?16/9:edit.format==='9:16'?9/16:1})`}}>{active?<><video ref={video} src={source} muted playsInline onLoadedMetadata={()=>syncVideo(video.current,active,position?.local||0)}/>{fading&&<video className="ve-overlay" ref={overlay} src={overlaySource} muted playsInline style={{opacity:Math.max(0,Math.min(1,(fading.end-cursor)/fading.overlap))}} onLoadedMetadata={()=>syncVideo(overlay.current,fading.clip,cursor-fading.start)}/>}</>:<div><h2>Tu historia empieza aquí</h2><p>Sube tus videos y añádelos a la línea de tiempo.</p></div>}</div><audio ref={audio} src={musicSource||undefined}/><div className="ve-transport"><button disabled={!active} onClick={()=>{if(playing)stop();else{if(cursor>=length){seek(0);setPlaying(true);video.current?.play().catch(()=>setPlaying(false));}else{setPlaying(true);video.current?.play().catch(()=>setPlaying(false));}}}}>{playing?'Pausar':'Reproducir'}</button><span>{stamp(cursor)} / {stamp(length)}</span></div><input className="ve-scrub" aria-label="Posición del montaje" type="range" min="0" max={length||1} step=".033333" value={cursor} onChange={e=>seek(Number(e.target.value))}/>
 <div className="ve-timeline-head"><h2>Línea de tiempo</h2><div><button disabled={!clip} onClick={split}>✂ Dividir</button><button disabled={!past.length} onClick={()=>{stop();setResult('');setFuture(f=>[edit,...f]);setEdit(past[past.length-1]);setPast(p=>p.slice(0,-1));setCursor(0);setDirty(true);}}>Deshacer</button><button disabled={!future.length} onClick={()=>{stop();setResult('');setPast(p=>[...p,edit]);setEdit(future[0]);setFuture(f=>f.slice(1));setCursor(0);setDirty(true);}}>Rehacer</button><label>Zoom<input aria-label="Zoom de la línea de tiempo" type="range" min="20" max="140" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label></div></div>
 <p className="ve-hint">Arrastra videos desde la biblioteca. Pulsa la regla para situar el cursor y usa ✂ Dividir. La fusión se elige entre dos tomas.</p>
 <div className="ve-timeline-scroll" ref={timelineScroll} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e)}><div className="ve-track" style={{width:trackWidth}}>
 <div className="ve-ruler" aria-label="Regla de segundos" onClick={e=>seek(Math.min(length,Math.max(0,(e.clientX-e.currentTarget.getBoundingClientRect().left)/zoom)))}>{Array.from({length:Math.ceil(trackWidth/zoom)+1},(_,i)=><span key={i} style={{left:i*zoom}}>{stamp(i)}</span>)}</div>
 <div className="ve-video-lane">{rows.map(({clip:c,start},i)=><button className="ve-timeline-clip" style={{left:start*zoom,width:duration(c)*zoom}} draggable={!busy} key={c.id} aria-label={`Toma ${i+1}: ${media.find(m=>m.id===c.mediaId)?.name}`} aria-pressed={selected===c.id} onDragStart={e=>{drag.current=c.id;e.dataTransfer.setData('text/plain',c.id);}} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,c.id)} onClick={e=>{setSelected(c.id);seek(Math.min(length,start+Math.max(0,(e.clientX-e.currentTarget.getBoundingClientRect().left)/zoom)));}}><strong>{i+1} · {media.find(m=>m.id===c.mediaId)?.name}</strong><video src={url(media.find(m=>m.id===c.mediaId))} muted preload="metadata" onLoadedMetadata={e=>{e.currentTarget.currentTime=c.start+.01;}}/><small>{stamp(duration(c))} · {c.speed}×</small></button>)}{!rows.length&&<p className="ve-drop-hint">Arrastra tus videos aquí para empezar</p>}</div>
 <div className="ve-transition-lane">{rows.slice(0,-1).map((r,i)=><label key={r.clip.id} style={{left:Math.max(0,(r.end-r.overlap/2)*zoom-48)}}><span>Unión {i+1} → {i+2}</span><select aria-label={`Transición después de toma ${i+1}`} value={r.clip.transition||0} onChange={e=>change({...edit,clips:edit.clips.map(c=>c.id===r.clip.id?{...c,transition:Number(e.target.value)}:c)})}><option value="0">Corte</option><option value="0.5">Fusión 0,5 s</option><option value="1">Fusión 1 s</option><option value="1.5">Fusión 1,5 s</option><option value="2">Fusión 2 s</option></select></label>)}</div>
 <div className="ve-audio-lane">{edit.music?<div style={{width:Math.min(length,edit.music.duration-edit.musicStart)*zoom}}>♫ {edit.music.name}</div>:<span>♫ Añade música desde la biblioteca</span>}</div>
 <div className="ve-playhead" style={{left:Math.min(cursor,length)*zoom}}><span/></div>
 </div></div>

 {clip&&<div className="ve-clip-controls"><h3>Fragmento {edit.clips.indexOf(clip)+1}</h3><div className="ve-fields"><label>Desde (s)<input aria-label="Desde" type="number" step=".1" min="0" max={clip.end-.1} value={clip.start} onChange={e=>update({start:Number(e.target.value)})}/></label><label>Hasta (s)<input aria-label="Hasta" type="number" step=".1" min={clip.start+.1} max={media.find(m=>m.id===clip.mediaId)?.duration} value={clip.end} onChange={e=>update({end:Number(e.target.value)})}/></label><label>Velocidad<select aria-label="Velocidad" value={clip.speed} onChange={e=>update({speed:Number(e.target.value)})}>{[.25,.5,1,1.5,2,4].map(s=><option key={s} value={s}>{s}×</option>)}</select></label></div><div className="ve-actions"><button onClick={split}>Dividir en el cursor</button>{[-1,1].map(d=><button key={d} disabled={!edit.clips[edit.clips.indexOf(clip)+d]} onClick={()=>change({...edit,clips:moveClip(edit.clips,clip.id,edit.clips[edit.clips.indexOf(clip)+d].id)})}>{d===-1?'← Antes':'Después →'}</button>)}<button onClick={()=>change({...edit,clips:edit.clips.filter(c=>c.id!==clip.id)})}>Eliminar fragmento</button></div></div>}
 </section></fieldset></main>;
}
