export type Media={id:string;name:string;file:Blob;duration:number};
export type Clip={id:string;mediaId:string;start:number;end:number;speed:number;transition?:number;transitionKind?:'linear'|'smooth'};
export type Edit={clips:Clip[];music:Media|null;musicStart:number;volume:number;format:'16:9'|'9:16'|'1:1';resolution:720|1080};
export const initialEdit:Edit={clips:[],music:null,musicStart:0,volume:.6,format:'16:9',resolution:720};
export const duration=(c:Clip)=>Math.max(1,Math.round((c.end-c.start)/c.speed*30))/30;
// A transition belongs to the outgoing clip. Clamp overlaps so three clips never overlap.
export function overlap(clips:Clip[],i:number){return i<clips.length-1?Math.max(0,Math.min(clips[i].transition||0,duration(clips[i])/2,duration(clips[i+1])/2)):0;}
export function timeline(clips:Clip[]){let start=0;return clips.map((clip,i)=>{const row={clip,start,end:start+duration(clip),overlap:overlap(clips,i)};start=row.end-row.overlap;return row;});}
export const totalDuration=(clips:Clip[])=>timeline(clips).at(-1)?.end||0;
export function locate(clips:Clip[],time:number){const rows=timeline(clips);for(let i=rows.length-1;i>=0;i--){if(time>=rows[i].start||i===0)return {index:i,offset:rows[i].start,local:Math.min(duration(clips[i]),Math.max(0,time-rows[i].start))};}return null;}
export function splitClip(c:Clip,local:number):Clip[]{const cut=c.start+Math.round(local*30)/30*c.speed;if(cut-c.start<.1||c.end-cut<.1)throw Error('Coloca el cursor dentro del clip, lejos de sus extremos.');return [{...c,end:cut,transition:0},{...c,id:crypto.randomUUID(),start:cut}];}
export function moveClip(clips:Clip[],id:string,target:string){const from=clips.findIndex(c=>c.id===id),to=clips.findIndex(c=>c.id===target);if(from<0||to<0)return clips;const copy=[...clips];copy.splice(to,0,...copy.splice(from,1));return copy;}
export function dimensions(edit:Edit){const side=edit.resolution;return edit.format==='1:1'?[side,side]:edit.format==='9:16'?[side,side===720?1280:1920]:[side===720?1280:1920,side];}
export function validate(edit:Edit,media:Media[]){if(!edit.clips.length)throw Error('Añade al menos un video a la línea de tiempo.');if(edit.clips.length>30||totalDuration(edit.clips)>120)throw Error('Esta primera versión admite hasta 30 fragmentos y 2 minutos de montaje.');for(const c of edit.clips){const m=media.find(m=>m.id===c.mediaId);if(!m||![c.start,c.end,c.speed,m.duration].every(Number.isFinite)||c.start<0||c.end>m.duration+.01||c.end-c.start<.1||c.speed<.25||c.speed>4||(c.transition!==undefined&&(!Number.isFinite(c.transition)||c.transition<0||c.transition>2)))throw Error('Revisa el recorte y la velocidad de los clips.');}if(edit.music&&(!Number.isFinite(edit.musicStart)||edit.musicStart<0||edit.musicStart>=edit.music.duration))throw Error('Revisa el inicio de la música.');}
export async function inspect(file:Blob,kind:'video'|'audio'):Promise<number>{return new Promise((resolve,reject)=>{const el=document.createElement(kind),url=URL.createObjectURL(file);const clean=()=>{el.onloadedmetadata=null;el.onerror=null;clearTimeout(timer);el.removeAttribute('src');el.load();URL.revokeObjectURL(url);};const timer=setTimeout(()=>{clean();reject(Error('No se pudo leer el archivo. Prueba MP4 o MP3.'));},15000);el.preload='metadata';el.onloadedmetadata=()=>{const value=el.duration;clean();if(Number.isFinite(value)&&value>0)resolve(value);else reject(Error('El archivo no tiene una duración válida.'));};el.onerror=()=>{clean();reject(Error('Formato no compatible con este navegador. Prueba MP4 (H.264) o MP3.'));};el.src=url;});}

export function blendProgress(progress:number,kind:Clip["transitionKind"]="linear"){const p=Math.max(0,Math.min(1,progress));return kind==="smooth"?p*p*(3-2*p):p;}
