import {act,fireEvent,render,within,cleanup} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import Clips from './Clips';
import type {Scene} from './model';
const {invoke}=vi.hoisted(()=>({invoke:vi.fn()}));
vi.mock('./fusion-cloud',()=>({listFusions:vi.fn(async()=>[])}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{functions:{invoke}}}));
afterEach(()=>{cleanup();vi.clearAllMocks();});
it('keeps cost and confirmation in the composer and sends results to the separate panel',async()=>{
 Object.defineProperty(AbortSignal,'timeout',{configurable:true,value:()=>new AbortController().signal});
 const panel=document.createElement('div');document.body.append(panel);
 const scene:Scene={id:'scene',name:'Cubierta',mode:'animate',startId:'render',endId:'',movement:'push',duration:5,format:'16:9',brief:'',prompt:'Reveal the roof',notes:'',promptBasis:''};
 const job={id:'job',sceneId:'scene',name:'Cubierta',model:'kling-video/v3.0/std/image-to-video',duration:5,state:'quoted',estimatedUsd:.347,url:null,expiresAt:''};
 let finish:(value:unknown)=>void=()=>{};
 invoke.mockImplementation((_name,{body})=>body.action==='list'?Promise.resolve({data:{jobs:[]}}):body.action==='quote'?Promise.resolve({data:{job}}):new Promise(resolve=>{finish=resolve;}));
 const view=render(<Clips scene={scene} blocked={false} resultsPanel={panel}/>);
 await within(panel).findByText('Tu video aparecerá aquí cuando lo envíes a generar.');
 fireEvent.click(within(view.container).getByText('Consultar costo de esta toma'));
 const quoteCall=invoke.mock.calls.find(([,args])=>args.body.action==='quote');
 expect(quoteCall?.[1].body.engine).toBe('standard');
 const generate=await within(view.container).findByText('Generar video · USD 0.347');
 expect(within(panel).queryByText('Generar video · USD 0.347')).toBeNull();
 expect(invoke.mock.calls.some(([,args])=>args.body.action==='start')).toBe(false);
 fireEvent.click(generate);
 const activity=await within(panel).findByRole('article',{name:'Estado de tu toma'});
 expect(within(activity).getByRole('status')).toHaveTextContent('Enviando');
 expect(view.container.querySelector('video')).toBeNull();
 await act(async()=>finish({data:{job:{...job,state:'completed',url:'https://example.com/clip.mp4'}}}));
 expect(within(activity).getByRole('status')).toHaveTextContent('Clip listo');
 panel.remove();
});

it('shows quality with its engine and sends the selected Kling tier for pricing',async()=>{
 Object.defineProperty(AbortSignal,'timeout',{configurable:true,value:()=>new AbortController().signal});
 const {newScene}=await import('./model');
 const scene={...newScene(),startId:'render',prompt:'Slow architectural reveal'};
 const job={id:'pro',sceneId:scene.id,name:scene.name,model:'kling-video/v3.0/pro/image-to-video',duration:5,state:'quoted',estimatedUsd:.462,url:null,expiresAt:''};
 invoke.mockImplementation((_name,{body})=>Promise.resolve({data:body.action==='list'?{jobs:[]}:{job}}));
 const view=render(<Clips scene={scene} blocked={false} resultsPanel={document.body}/>);
 const selector=within(view.container).getByLabelText('Calidad y motor');
 expect(selector).toHaveValue('standard');
 fireEvent.change(selector,{target:{value:'premium'}});
 expect(within(view.container).getByText('Más detalle y consistencia · una o dos imágenes. Sin audio.')).toBeTruthy();
 fireEvent.click(within(view.container).getByText('Consultar costo de esta toma'));
 await within(view.container).findByText('Generar video · USD 0.462');
 const quoteCall=invoke.mock.calls.find(([,args])=>args.body.action==='quote');
 expect(quoteCall?.[1].body.engine).toBe('premium');
});

it('loads saved fusions again on mount and keeps them separate from paid jobs',async()=>{
 const {listFusions}=await import('./fusion-cloud');
 vi.mocked(listFusions).mockResolvedValue([{id:'fusion',name:'Fusión guardada',duration:5,url:'https://example.com/saved.mp4',storage_path:'owner/fusion.mp4',created_at:''}]);
 invoke.mockResolvedValue({data:{jobs:[]}});
 const panel=document.createElement('div');document.body.append(panel);
 const {newScene}=await import('./model');
 const view=render(<Clips scene={newScene()} blocked={false} resultsPanel={panel}/>);
 expect(await within(panel).findByText('Fusión guardada')).toBeTruthy();
 view.unmount();
 render(<Clips scene={newScene()} blocked={false} resultsPanel={panel}/>);
 expect(await within(panel).findByRole('link',{name:'Abrir / descargar fusión'})).toHaveAttribute('href','https://example.com/saved.mp4');
 panel.remove();
});

it('shows a restored pending job above history and refreshes it without generating again',async()=>{
 const {newScene}=await import('./model');
 const activityPanel=document.createElement('div'),panel=document.createElement('div');
 document.body.append(activityPanel,panel);
 const job={id:'pending',sceneId:'scene',name:'Acercamiento al proyecto',model:'minimax',duration:10,state:'queued',estimatedUsd:.2,url:null,expiresAt:'',createdAt:new Date().toISOString()};
 invoke.mockImplementation((_name,{body})=>Promise.resolve({data:body.action==='status'?{job:{...job,state:'completed',url:'https://example.com/done.mp4'}}:{jobs:[job]}}));
 const scroll=vi.fn();
 Element.prototype.scrollIntoView=scroll;
 const view=render(<Clips scene={newScene()} blocked={false} resultsPanel={panel} activityPanel={activityPanel}/>);
 const card=await within(activityPanel).findByRole('article',{name:'Estado de tu toma'});
 expect(within(card).getByRole('status')).toHaveTextContent('En cola');
 expect(activityPanel.compareDocumentPosition(panel)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
 fireEvent.click(within(view.container).getByRole('button',{name:'Ver estado de «Acercamiento al proyecto» →'}));
 expect(scroll).toHaveBeenCalled();
 fireEvent.click(within(card).getByRole('button',{name:'Actualizar estado de la toma'}));
 expect(await within(card).findByRole('link',{name:'Abrir / descargar esta toma'})).toHaveAttribute('href','https://example.com/done.mp4');
 expect(within(card).getByRole('status')).toHaveTextContent('Clip listo');
 expect(invoke.mock.calls.some(([,args])=>['start','quote'].includes(args.body.action))).toBe(false);
 activityPanel.remove();panel.remove();
});
