export type PosterKind =
  | "portrait"
  | "product"
  | "none"
  | "group"
  | "scene"
  | "photo"
  | "pets"
  | "architecture";
export type CatalogPoster = {
  id: string;
  name: string;
  category: string;
  direction: string;
  title: string;
  subtitle: string;
  color: string;
  kind: PosterKind;
  image: string;
  reference: boolean;
  approved: boolean;
  remix: string;
  ratio: string;
  sourceNote: string;
};
export const CATALOG: CatalogPoster[] = [
  {
    "id": "P01",
    "name": "Conferencista geométrico",
    "category": "Retratos",
    "direction": "Retrato recortado en primer plano, círculos y diagonales de colores detrás, titular negro condensado arriba y banda vertical lateral. Fondo marfil.",
    "title": "DALE DIRECCIÓN A LA IMAGINACIÓN",
    "subtitle": "",
    "color": "#1658c5",
    "kind": "portrait",
    "image": "/poster-lab/P01.png",
    "reference": true,
    "approved": true,
    "remix": "Crea un póster vertical para presentar a un conferencista. Fondo marfil cálido. Arriba, titular negro muy grande y condensado en dos líneas; debajo, lema y una línea temática junto a tres puntos azul, rojo y negro. En el centro inferior, recorta el retrato sobre círculos y diagonales superpuestos naranja y rojo. Una banda azul Klein ocupa toda la altura del borde derecho: nombre vertical, cargo en pequeño, líneas finas y una flecha diagonal blanca. Conserva el contraste y la relación entre retrato, titular y banda lateral.",
    "ratio": "2:3",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P02",
    "name": "Producto editorial",
    "category": "Productos",
    "direction": "Producto protagonista suspendido con sombra suave, fondo marfil, anotaciones laterales finas, sello circular y titular grande abajo. Azul con acento naranja.",
    "title": "ESCUCHA DE OTRA MANERA",
    "subtitle": "",
    "color": "#154da8",
    "kind": "product",
    "image": "/poster-lab/P02.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical 2:3 para una sesión de escucha íntima. Fondo blanco cálido. En el margen izquierdo, un carril vertical azul con número de edición, nombre, fecha, horario y lema, separados por puntos y líneas finas. En el centro, unos auriculares retro azul profundo translúcido con cable naranja enrollado flotan con sombra suave; cuando se aporte un producto, sustituye los auriculares por ese producto. Cerca de la esquina superior derecha, un sello circular con pequeñas palabras y un punto naranja. El gran titular azul en negrita ancla la mitad inferior sobre dos columnas pequeñas de información. Mantén espacio libre, luz de estudio suave y precisión editorial.",
    "ratio": "2:3",
    "sourceNote": "Versión de trabajo en español basada en el remix visible y la imagen. No es una transcripción literal."
  },
  {
    "id": "P03",
    "name": "Minimal diagonal",
    "category": "Tipográficos",
    "direction": "Fondo de papel marfil, gran bloque diagonal verde oscuro arriba a la derecha, título negro a la izquierda, amplio espacio vacío y tres columnas inferiores.",
    "title": "MANUAL DE CAMPO NOCTURNO",
    "subtitle": "",
    "color": "#164b3e",
    "kind": "none",
    "image": "/poster-lab/P03.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster de exposición vertical 3:4. Fondo de papel blanco roto, con un gran bloque diagonal verde bosque oscuro en la esquina superior derecha. Cabecera pequeña arriba a la izquierda y una raya verde corta. El título negro grotesco, enorme, se apila en tres líneas a media altura del lado izquierdo, seguido por una breve descripción. El tercio inferior se divide en tres columnas con filetes finos: inauguración y programa; exposición y número de obras; lugar y fechas. Pequeñas rayas verdes encabezan las columnas. Pie con línea horizontal, créditos pequeños y un cuadrado verde a la derecha.",
    "ratio": "3:4",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P04",
    "name": "Collage eléctrico",
    "category": "Eventos",
    "direction": "Fondo rojo, dos retratos en recorte central de rayo con borde blanco, tipografía crema condensada y gran texto vertical lateral.",
    "title": "ECO ESTÁTICO",
    "subtitle": "",
    "color": "#b80c09",
    "kind": "group",
    "image": "/poster-lab/P04.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical 9:16 de una noche de club, sobre fondo rojo intenso a sangre. A la izquierda, letras crema muy grandes y condensadas con el título y la fecha debajo; a la derecha, el día de la semana gigante y vertical. En el centro, un marco fotográfico irregular en forma de rayo, delineado en blanco, contiene dos retratos de moda: uno arriba y otro abajo. Usa las fotos aportadas cuando existan. Cerca de la parte superior aparece una frase manuscrita inclinada y un bloque pequeño con aforo y entrada. Abajo, hora de apertura, nombre del local en negrita y una línea de tres palabras temáticas. Mantén el rayo, las proporciones y la paleta roja y crema.",
    "ratio": "9:16",
    "sourceNote": "Versión de trabajo en español basada en el remix visible y la imagen. No es una transcripción literal."
  },
  {
    "id": "P05",
    "name": "Cine nocturno",
    "category": "Eventos",
    "direction": "Póster cinematográfico de textura vintage, negro y naranja quemado, escena nocturna cálida central, título de serifas gruesas y programa en filas inferiores.",
    "title": "LAS CALLES LUMINOSAS",
    "subtitle": "",
    "color": "#bc582b",
    "kind": "scene",
    "image": "/poster-lab/P05.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical 3:4 para un festival de cortometrajes de fantasía urbana. Fondo casi negro con textura de impresión antigua. Arriba, una línea pequeña de sede y duración, seguida de un título enorme de serifas gruesas color crema con sombra desplazada roja. Debajo, fechas y días de la semana separados por líneas y una etiqueta naranja. La imagen central es una ilustración nocturna cálida: callejón estrecho adoquinado, figura con sombrero que se aleja portando un farol y ventanas luminosas al fondo, salvo que se aporte otra escena. Debajo, programa en tres filas con días, horas, títulos, cantidad de películas y duración. Al pie, tres columnas para lugar, entradas y organizadores. Conserva negros profundos y naranja quemado.",
    "ratio": "3:4",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P06",
    "name": "Tipografía gigante",
    "category": "Tipográficos",
    "direction": "Fondo azul saturado, título blanco condensado que domina la composición, pequeños acentos amarillos y cronograma horizontal inferior.",
    "title": "CAMINATA NOCTURNA",
    "subtitle": "",
    "color": "#0863c5",
    "kind": "none",
    "image": "/poster-lab/P06.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical para caminatas nocturnas de verano. Fondo azul cobalto saturado. Una cabecera pequeña enfrenta el nombre de la serie con la edición; una línea fina los subraya. Fechas y horario encima del enorme titular blanco grotesco y condensado en dos líneas, que domina casi toda la composición. Debajo, subtítulo blanco junto a una etiqueta amarilla con la distancia. Sigue una línea de tiempo horizontal de cuatro paradas con puntos, horas y lugares; la última se destaca en amarillo. El pie contiene distancia total, duración, tipo de actividad y entrada, con una pequeña caja blanca para el organizador.",
    "ratio": "2:3",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P07",
    "name": "Retrato suizo",
    "category": "Retratos",
    "direction": "Papel blanco, círculo rojo con retrato de perfil en semitono, tipografía negra muy pesada entrelazada con el retrato y agenda alineada lateralmente. Sin degradados.",
    "title": "NOTAS SOBRE CREATIVIDAD",
    "subtitle": "",
    "color": "#ed3024",
    "kind": "portrait",
    "image": "/poster-lab/P07.png",
    "reference": true,
    "approved": true,
    "remix": "Crea un póster vertical 2:3 para una conferencia creativa, de estilo suizo internacional. Fondo de papel blanco, tipografía negra sans serif ultrapesada y rojo de alta saturación. El retrato de perfil en semitono se sitúa dentro de un gran círculo rojo. Distribuye el nombre y el título en tres grandes segmentos entrelazados con el retrato; la última palabra del título es roja. Fecha y día a la izquierda, agenda de cuatro entradas ajustada al lado derecho. Usa jerarquía clara y un título que se lea a distancia. No uses degradados, brillos tecnológicos ni fondos fotográficos. Adapta el retrato a la persona aportada conservando su identidad.",
    "ratio": "2:3",
    "sourceNote": "Versión de trabajo en español basada en el remix visible y la imagen. No es una transcripción literal."
  },
  {
    "id": "P08",
    "name": "Ondas experimentales",
    "category": "Abstractos",
    "direction": "Fondo blanco, título negro condensado, palabra secundaria en contorno violeta, cintas curvas de líneas verdes con efecto moiré y pequeñas marcas técnicas.",
    "title": "SEÑALES DESPLAZADAS",
    "subtitle": "",
    "color": "#99df14",
    "kind": "none",
    "image": "/poster-lab/P08.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster experimental vertical 3:4 para una serie de un instituto de medios. Fondo blanco, cabecera pequeña arriba a la izquierda. Titular negro grotesco enorme en dos líneas; debajo, una palabra grande delineada en violeta. En el centro izquierdo, título secundario condensado, fecha violeta entre llaves y dos líneas pequeñas. A la derecha, anotación de tres conceptos con una flecha hacia la obra. La mitad derecha se construye con cintas curvas verde lima, formadas por muchas líneas paralelas finas en flujos tipo moiré, que sugieren una señal desplazada. Añade índices discretos, cruces, escalas y marcas técnicas violetas. El pie separa con filetes el nombre del laboratorio en negro sólido y su descripción en letras de contorno.",
    "ratio": "3:4",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P09",
    "name": "Galería fotográfica",
    "category": "Fotográficos",
    "direction": "Composición editorial blanca con serifas altas, espacio amplio arriba, información en tres columnas y fotografía documental ocupando la mitad inferior.",
    "title": "NUEVAS ESCENAS URBANAS",
    "subtitle": "",
    "color": "#444444",
    "kind": "photo",
    "image": "/poster-lab/P09.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical 2:3 para una exposición de fotografía callejera. Fondo blanco con mucho espacio libre. Arriba a la izquierda, gran titular en serifas altas; al centro, tema, título secundario y fechas; a la derecha, lema vertical en varias líneas. Más abajo, bloque informativo en tres columnas con fecha y hora, charla y breve descripción, sede y entrada. La mitad inferior está dominada por una fotografía documental: peatón con paraguas transparente cruzando un paso de cebra una noche lluviosa, con luces del tráfico barridas por el movimiento, o la foto aportada. Pie con tres créditos pequeños alineados.",
    "ratio": "2:3",
    "sourceNote": "Versión de trabajo en español basada en el remix visible y la imagen. No es una transcripción literal."
  },
  {
    "id": "P10",
    "name": "Retrato fragmentado",
    "category": "Retratos",
    "direction": "Retrato dividido en cuatro tiras horizontales ligeramente desplazadas, tonos sepia y gris cálido, papel envejecido, grano y detalles de archivo.",
    "title": "ESTRATOS DE MEMORIA",
    "subtitle": "",
    "color": "#b69a70",
    "kind": "portrait",
    "image": "/poster-lab/P10.png",
    "reference": true,
    "approved": true,
    "remix": "Crea un póster vertical 2:3 para un evento de cine experimental. El elemento principal es un retrato frontal en blanco y negro, dividido en cuatro tiras horizontales de película ligeramente desalineadas: ojos, puente de la nariz y boca se recomponen entre las tiras. Intercala un círculo de papel marrón y pequeños números de archivo. Usa papel envejecido gris cálido, fotografía negro sepia, puntos finos de semitono y grano de fotocopia. Información del evento arriba y abajo, con fecha, sede y breves anotaciones de archivo. Añade un detalle botánico y una ampliación circular si encajan con la foto. Debe parecer un cartel de proyección de una institución independiente de fotografía.",
    "ratio": "2:3",
    "sourceNote": "Versión de trabajo en español basada en el remix visible y la imagen. No es una transcripción literal."
  },
  {
    "id": "P11",
    "name": "Revista de arquitectura",
    "category": "Fotográficos",
    "direction": "Fondo gris claro, titular negro condensado a la izquierda, collage de tres fotografías en blanco y negro y número de edición grande en amarillo lima.",
    "title": "COMPARTIR A OTRA ESCALA",
    "subtitle": "",
    "color": "#c9e92b",
    "kind": "photo",
    "image": "/poster-lab/P11.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical 2:3 para una serie de charlas de arquitectura, como una página editorial de revista. Fondo gris claro, gran titular negro condensado a la izquierda y dos subtítulos debajo separados por pequeños cuadrados lima. Arriba a la derecha, número de edición enorme amarillo chartreuse junto a fecha, horario y sala. En la mitad derecha y zona inferior, collage de tres fotos documentales en blanco y negro: una persona sobre una maqueta, otra estudiando planos en una escalera y una figura cruzando una puerta; reemplázalas por las imágenes aportadas. Una barra informativa inferior presenta al ponente, su cargo y breve introducción, con pequeño dibujo lineal de mobiliario. Pie con etiquetas separadas por barras y cuadrados lima.",
    "ratio": "2:3",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P12",
    "name": "Conferencia en bloques",
    "category": "Eventos",
    "direction": "Mitad superior crema con retrato en blanco y negro y presentación del ponente. Mitad inferior dividida en bloques mostaza y verde apagado con programa y datos.",
    "title": "REIMAGINAR LA CIUDAD",
    "subtitle": "",
    "color": "#d0a749",
    "kind": "portrait",
    "image": "/poster-lab/P12.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical dividido en dos partes para el foro inaugural de una conferencia. La mitad superior tiene fondo crema, una cabecera pequeña y un logotipo circular si se aporta, un bloque de presentación del invitado y una cita sobre la ciudad, junto a un retrato en blanco y negro mirando a la distancia. La mitad inferior se divide en un panel amarillo mostaza a la izquierda, con el gran título del tema y la lista de participantes, y un panel verde apagado a la derecha, con organizadores, fecha y sede. Una franja oscura inferior reúne fecha, hora y lugar. Conserva la estructura de dos mitades y sus bloques de color.",
    "ratio": "2:3",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P13",
    "name": "Mascotas y compañía",
    "category": "Fotográficos",
    "direction": "Cielo azul, mascotas de espaldas sobre muro blanco, título blanco grande arriba, trazos dibujados suaves y pie editorial negro sobre blanco.",
    "title": "UN HOGAR",
    "subtitle": "",
    "color": "#086dc9",
    "kind": "pets",
    "image": "/poster-lab/P13.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical 3:4 sobre compañía y mascotas para redes sociales. Fondo de cielo azul limpio. Arriba, cabecera pequeña en tres columnas. A la izquierda, enorme título blanco grotesco en dos líneas; a la derecha, lema vertical separado por reglas blancas finas. En el centro, cinco gatos de colores distintos vistos de espaldas, sentados en fila sobre un muro blanco, mirando al cielo; si se aportan mascotas, usa esas mascotas y su número real. Añade pocos arcos blancos dibujados a mano sobre ellas. La zona inferior blanca contiene dos bloques pequeños con puntos negros, un titular negro condensado y dos aros azules entrelazados junto a un lema corto.",
    "ratio": "3:4",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P14",
    "name": "Música en semitono",
    "category": "Fotográficos",
    "direction": "Papel crema, titular de serifas, banda central cian con retrato musical en semitono negro, pequeñas etiquetas y créditos ordenados abajo.",
    "title": "EL RUIDO APRENDE A CANTAR",
    "subtitle": "",
    "color": "#10afc3",
    "kind": "portrait",
    "image": "/poster-lab/P14.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster de película independiente vertical aproximadamente 5:7. Fondo crema con grano de papel. En la parte superior, una etiqueta redondeada y especificaciones pequeñas a la derecha. Gran titular con serifas a la izquierda junto a tres frases breves en cursiva con pequeños cuadrados cian. Una banda cian ancha central contiene una foto en semitono negro de un cantante ante un micrófono, una etiqueta negra y un título vertical. Debajo, franja negra con un lema corto. El bloque inferior se divide en tres columnas mediante líneas discontinuas: estreno, autor y reseña. Remata con el nombre de la película en letras cian grandes y una palabra manuscrita negra superpuesta. Añade asteriscos y pequeños rayos cian con moderación.",
    "ratio": "5:7",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P15",
    "name": "Arquitectura de impacto",
    "category": "Fotográficos",
    "direction": "Tipografía negra condensada, gran círculo amarillo fluorescente, fotografía arquitectónica horizontal en blanco y negro al centro y fechas grandes debajo.",
    "title": "CIUDAD PLEGADA",
    "subtitle": "",
    "color": "#e1df12",
    "kind": "architecture",
    "image": "/poster-lab/P15.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical para una exposición de fotografía arquitectónica. Fondo blanco roto. Cabecera con museo y edición separados por una línea. En la mitad superior, título negro muy grande y condensado en dos líneas junto a un gran círculo amarillo fluorescente; sobre el círculo, un lema pequeño y título vertical. El centro contiene una fotografía horizontal en blanco y negro de arquitectura brutalista de hormigón, pliegues geométricos de escaleras y muros inclinados, o la arquitectura aportada. Debajo, fechas sobredimensionadas y horario pequeño a la derecha. Tres columnas inferiores para sede, entrada y curaduría; franja negra final con créditos amarillos.",
    "ratio": "3:4",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P16",
    "name": "Geometría en papel",
    "category": "Abstractos",
    "direction": "Bloque azul con bordes de papel rasgado, cinta geométrica crema, medio sol naranja y pequeño rombo amarillo. Pie marfil con serifas y fechas.",
    "title": "ARCHIVO FLOTANTE",
    "subtitle": "",
    "color": "#4199bc",
    "kind": "none",
    "image": "/poster-lab/P16.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster de exposición vertical 3:4. Los dos tercios superiores son un único bloque azul lago con bordes de papel rasgado y textura de impresión desgastada. Dentro, una larga forma geométrica de cinta crema que se pliega en perspectiva, medio sol naranja rojizo y un pequeño rombo amarillo. En la esquina superior izquierda, lema en líneas verticales cortas; cruces finas de dibujo técnico en las esquinas. El tercio inferior tiene fondo crema cálido: columna izquierda con horario y fechas; a la derecha, un gran título en serifas estrechas junto a una etiqueta vertical. Pie con créditos muy pequeños.",
    "ratio": "3:4",
    "sourceNote": "Versión de trabajo en español basada en el remix visible y la imagen. No es una transcripción literal."
  },
  {
    "id": "P17",
    "name": "Archivo cultural",
    "category": "Tipográficos",
    "direction": "Papel crema con bloque naranja irregular, titular condensado dividido en columnas, diagonales blancas, acento verde y zona inferior de ponentes.",
    "title": "ESCUCHAR DE NUEVO LA CIUDAD",
    "subtitle": "",
    "color": "#e78b14",
    "kind": "none",
    "image": "/poster-lab/P17.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical 3:4 para un foro de archivo sonoro urbano. Papel crema texturado. El titular condensado negro se divide en columnas sobre un bloque naranja irregular dominante; pequeñas frases y diagonales blancas atraviesan ese bloque. Un carril izquierdo acredita al presentador, anfitrión y edición separados por líneas. Debajo, subtítulo negro en varias líneas y tres columnas para los ponentes, cada una con nombre y cargo. A la derecha, polígono verde apagado con círculo negro de entrada y dos diagonales blancas. Un gran semicírculo amarillo inferior contiene la sede, capacidad, fecha y horario. Mantén textura analógica y retícula editorial.",
    "ratio": "3:4",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P18",
    "name": "Retrato futurista",
    "category": "Retratos",
    "direction": "Retrato protagonista con estilismo azul y plata sosteniendo prisma luminoso verde; fondo claro, títulos negros grandes, acentos lima y marcas geométricas.",
    "title": "FRONTERA SENSORIAL",
    "subtitle": "",
    "color": "#b7e825",
    "kind": "portrait",
    "image": "/poster-lab/P18.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical 3:4 de exposición de arte. Fondo claro. Una insignia lima redondeada arriba a la derecha con el programa y una etiqueta debajo. A la izquierda, título negro condensado enorme en dos líneas, subrayado lima y subtítulo en negrita, seguido de una descripción corta. En el borde derecho, etiqueta de apertura y fechas verticales. El retrato protagonista lleva cuello alto plateado metálico y chaleco azul Klein estructurado; sostiene un prisma triangular de vidrio verde luminoso que emite haces de luz. Conserva la identidad de la persona aportada. Añade pequeños cuadros negros, marcas de registro, escalas azules y líneas geométricas. Información de sede y código abajo a la izquierda; crédito centrado al pie.",
    "ratio": "3:4",
    "sourceNote": "La captura corta parte del remix. Versión de trabajo en español basada en el texto visible y la imagen; falta cotejar el final original."
  },
  {
    "id": "P19",
    "name": "Foto y acento rojo",
    "category": "Fotográficos",
    "direction": "Fotografía en blanco y negro a sangre con área clara superior, titular rojo condensado grande, subtítulo manuscrito negro y datos pequeños en esquinas.",
    "title": "MAREA BAJA",
    "subtitle": "",
    "color": "#e43113",
    "kind": "photo",
    "image": "/poster-lab/P19.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster fotográfico vertical 3:4. Una fotografía costera en blanco y negro llena el fondo: cormorán con alas extendidas sobre una cuerda de amarre y borde de muelle envejecido abajo a la izquierda, o la foto aportada. Aprovecha el área superior clara para un título rojo muy grande y condensado en dos líneas, junto a un subtítulo negro manuscrito en cursiva. En las esquinas superiores, datos de archivo, exposición, fechas y galería en mayúsculas pequeñas. Abajo, nota curatorial a la izquierda y entrada y horario a la derecha, con una línea roja fina al pie.",
    "ratio": "3:4",
    "sourceNote": "Versión de trabajo en español basada en el remix visible y la imagen. No es una transcripción literal."
  },
  {
    "id": "P20",
    "name": "Texto en perspectiva",
    "category": "Fotográficos",
    "direction": "Fotografía cenital conservada, titular integrado en perspectiva sobre una superficie y notas de diario discretas. Letras negras o blancas sin tapar personas.",
    "title": "DISEÑO INCLUSIVO",
    "subtitle": "",
    "color": "#b63427",
    "kind": "photo",
    "image": "/poster-lab/P20.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster vertical 3:4 como diario visual de tipografía urbana. Llena todo el encuadre con una foto cenital de un paso peatonal rojo y blanco, o con la foto aportada. Mantén la fotografía sin alterar: sin gradación de color ni filtros; todo el diseño ocurre en la capa de texto. Integra un gran titular industrial sans serif en la superficie siguiendo la perspectiva de las franjas, como letras pintadas sobre el suelo, evitando deliberadamente a los peatones. A lo largo de bordillos y franjas, añade fecha, horas, notas matinales y unas pocas líneas de diario en letra pequeña. Usa exclusivamente texto blanco y negro. El resultado debe ser contenido y conservar la observación urbana de la foto.",
    "ratio": "3:4",
    "sourceNote": "Versión de trabajo en español basada en el remix visible y la imagen. No es una transcripción literal."
  },
  {
    "id": "P21",
    "name": "Naturaleza con amor",
    "category": "Fotográficos",
    "direction": "Póster de naturaleza con fondo marfil, azul cielo y verde hoja. Cabecera pequeña espaciada, FOTOGRAFÍA en azul, Con en letra delicada y un gran AMOR con la fotografía visible dentro de las letras. Abajo, un gorrión marrón, gris y blanco en una rama diagonal con flores blancas y hojas verdes, sobre cielo azul; pequeño código editorial en la esquina inferior derecha. Mantén la estética de revista, el grano fino y una sensación fresca y contenida.",
    "title": "FOTOGRAFÍA CON AMOR",
    "subtitle": "",
    "color": "#649bd1",
    "kind": "photo",
    "image": "/poster-lab/P21.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Póster de naturaleza con fondo marfil, azul cielo y verde hoja. Cabecera pequeña espaciada, FOTOGRAFÍA en azul, Con en letra delicada y un gran AMOR con la fotografía visible dentro de las letras. Abajo, un gorrión marrón, gris y blanco en una rama diagonal con flores blancas y hojas verdes, sobre cielo azul; pequeño código editorial en la esquina inferior derecha. Mantén la estética de revista, el grano fino y una sensación fresca y contenida. Usa textos en español y conserva el diseño y los colores salvo cambios expresamente indicados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación en español del remix visible y de la referencia suministrada. Las partes ocultas de la captura no se transcriben literalmente."
  },
  {
    "id": "P22",
    "name": "Señal en movimiento",
    "category": "Retratos",
    "direction": "Póster de exposición de laboratorio visual con fondo amarillo intenso. Cabecera NOTA DE CAMPO 07 y fecha bajo una línea fina. Arriba una pequeña fotografía de manos entrelazadas y mangas azules en un marco de esquinas redondas. Título SEÑAL FUGAZ en grandes letras negras finas. Retrato principal recortado en arco: una persona de pelo plateado y chaqueta azul ajusta el cuello de perfil, sobre gris y con estelas horizontales de movimiento. Pie con laboratorio, edición, círculo negro ENTRA y lema sobre ecos fugaces de la ciudad.",
    "title": "SEÑAL FUGAZ",
    "subtitle": "",
    "color": "#efef08",
    "kind": "portrait",
    "image": "/poster-lab/P22.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Póster de exposición de laboratorio visual con fondo amarillo intenso. Cabecera NOTA DE CAMPO 07 y fecha bajo una línea fina. Arriba una pequeña fotografía de manos entrelazadas y mangas azules en un marco de esquinas redondas. Título SEÑAL FUGAZ en grandes letras negras finas. Retrato principal recortado en arco: una persona de pelo plateado y chaqueta azul ajusta el cuello de perfil, sobre gris y con estelas horizontales de movimiento. Pie con laboratorio, edición, círculo negro ENTRA y lema sobre ecos fugaces de la ciudad. Usa textos en español y conserva el diseño y los colores salvo cambios expresamente indicados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación en español del remix visible y de la referencia suministrada. Las partes ocultas de la captura no se transcriben literalmente."
  },
  {
    "id": "P23",
    "name": "Montaña serena",
    "category": "Abstractos",
    "direction": "Póster de exposición de objetos orientales contemporáneos y cultura del té. Fondo de papel cálido, gran título serif LA MONTAÑA SERENA arriba a la izquierda y subtítulo OBJETOS · TÉ · EL ESPACIO ENTRE AMBOS. Nombre de la exposición, fechas y primavera arriba a la derecha. Mitad inferior con paisaje de tinta: montañas en capas disueltas en niebla y un pino antiguo en primer plano. Poema vertical a la derecha, dos pequeños sellos rojos. Créditos en columnas con líneas finas al pie. Amplio espacio vacío, silencio visual, negro y grises.",
    "title": "LA MONTAÑA SERENA",
    "subtitle": "",
    "color": "#ad583d",
    "kind": "scene",
    "image": "/poster-lab/P23.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Póster de exposición de objetos orientales contemporáneos y cultura del té. Fondo de papel cálido, gran título serif LA MONTAÑA SERENA arriba a la izquierda y subtítulo OBJETOS · TÉ · EL ESPACIO ENTRE AMBOS. Nombre de la exposición, fechas y primavera arriba a la derecha. Mitad inferior con paisaje de tinta: montañas en capas disueltas en niebla y un pino antiguo en primer plano. Poema vertical a la derecha, dos pequeños sellos rojos. Créditos en columnas con líneas finas al pie. Amplio espacio vacío, silencio visual, negro y grises. Usa textos en español y conserva el diseño y los colores salvo cambios expresamente indicados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación en español del remix visible y de la referencia suministrada. Las partes ocultas de la captura no se transcriben literalmente."
  },
  {
    "id": "P24",
    "name": "Vida lenta",
    "category": "Ilustrados",
    "direction": "Póster de festival comunitario de vida lenta sobre crema cálido. Cabecera naranja, enorme título azul marino VIDA LENTA a la izquierda, lema HAZ QUE CADA DÍA SE SIENTA TUYO a la derecha, fechas naranjas y talleres en azul. Ilustraciones manuales a dos tintas de tetera con tazas, planta, lámpara, tijeras, lana y tejido, naranjas, regadera, cuchara, agujas y cuaderno. Distribución aireada como grabado artesanal, textura sutil. Pie con fechas, plaza, organizadores e inscripciones. Objetos y textos en capas separadas.",
    "title": "VIDA LENTA",
    "subtitle": "",
    "color": "#c95413",
    "kind": "none",
    "image": "/poster-lab/P24.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Póster de festival comunitario de vida lenta sobre crema cálido. Cabecera naranja, enorme título azul marino VIDA LENTA a la izquierda, lema HAZ QUE CADA DÍA SE SIENTA TUYO a la derecha, fechas naranjas y talleres en azul. Ilustraciones manuales a dos tintas de tetera con tazas, planta, lámpara, tijeras, lana y tejido, naranjas, regadera, cuchara, agujas y cuaderno. Distribución aireada como grabado artesanal, textura sutil. Pie con fechas, plaza, organizadores e inscripciones. Objetos y textos en capas separadas. Usa textos en español y conserva el diseño y los colores salvo cambios expresamente indicados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación en español del remix visible y de la referencia suministrada. Las partes ocultas de la captura no se transcriben literalmente."
  },
  {
    "id": "P25",
    "name": "Cine juvenil",
    "category": "Fotográficos",
    "direction": "Póster de cine independiente juvenil. A la derecha, fotografía documental de alto contraste de dos jóvenes corriendo, en negro y amarillo ácido poco saturado. A la izquierda, columna vertical estrecha con CANCIONES SIN TERMINAR y JUVENTUD Y ROCK. Papel blanco cálido, puntos de semitono gruesos, grano de película y registro de tinta imperfecto. Abajo fecha, dirección y reseña en columnas; enorme título AVENIDA con firma Eco superpuesta. Mantén la legibilidad de fechas y créditos; evita iluminación de superproducción.",
    "title": "AVENIDA",
    "subtitle": "",
    "color": "#dddd00",
    "kind": "group",
    "image": "/poster-lab/P25.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Póster de cine independiente juvenil. A la derecha, fotografía documental de alto contraste de dos jóvenes corriendo, en negro y amarillo ácido poco saturado. A la izquierda, columna vertical estrecha con CANCIONES SIN TERMINAR y JUVENTUD Y ROCK. Papel blanco cálido, puntos de semitono gruesos, grano de película y registro de tinta imperfecto. Abajo fecha, dirección y reseña en columnas; enorme título AVENIDA con firma Eco superpuesta. Mantén la legibilidad de fechas y créditos; evita iluminación de superproducción. Usa textos en español y conserva el diseño y los colores salvo cambios expresamente indicados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación en español del remix visible y de la referencia suministrada. Las partes ocultas de la captura no se transcriben literalmente."
  },
  {
    "id": "P26",
    "name": "Concierto ilustrado",
    "category": "Ilustrados",
    "direction": "Póster de primer concierto solista de guitarrista. Tercio superior ilustrado a mano: hombre con gorra roja y guitarra acústica a la espalda subiendo una colina verde, cielo turquesa y nubes blancas. Franja crema central con PRIMER CONCIERTO en banda verde oscuro, gafas grandes ilustradas y lugar del evento. Barra con año, fecha, día y hora; debajo entradas y contacto. Abajo terreno rosa, piernas con calcetines rayados, peces blancos y banda diagonal con el nombre del artista. Mantén textura de impresión y paleta turquesa, crema, verde, rosa y marrón.",
    "title": "PRIMER CONCIERTO",
    "subtitle": "",
    "color": "#075e65",
    "kind": "scene",
    "image": "/poster-lab/P26.png",
    "reference": true,
    "approved": false,
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Póster de primer concierto solista de guitarrista. Tercio superior ilustrado a mano: hombre con gorra roja y guitarra acústica a la espalda subiendo una colina verde, cielo turquesa y nubes blancas. Franja crema central con PRIMER CONCIERTO en banda verde oscuro, gafas grandes ilustradas y lugar del evento. Barra con año, fecha, día y hora; debajo entradas y contacto. Abajo terreno rosa, piernas con calcetines rayados, peces blancos y banda diagonal con el nombre del artista. Mantén textura de impresión y paleta turquesa, crema, verde, rosa y marrón. Usa textos en español y conserva el diseño y los colores salvo cambios expresamente indicados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación en español del remix visible y de la referencia suministrada. Las partes ocultas de la captura no se transcriben literalmente."
  },
  {
    "id": "P27",
    "name": "Movimiento naranja",
    "category": "Retratos",
    "title": "GIRO",
    "subtitle": "",
    "color": "#ed9213",
    "kind": "portrait",
    "image": "/poster-lab/P27.png",
    "reference": true,
    "approved": false,
    "direction": "Retrato editorial monocromo de cuerpo entero: mujer de pelo corto con camisa holgada y pantalón ancho sostiene una esfera de cristal a la altura de los ojos. Fondo marfil cálido, grandes letras de contorno apiladas a la izquierda, bloques naranjas detrás y aro naranja a la derecha. Cabecera VELORA / NOTAS DE CAMPO, fecha ABRIL 2027, lema LA FORMA CAMBIA CUANDO MIRAS. VE DESPACIO. OBSERVA MÁS. Retículas finas, índices 04 27 01 y 12 46 59, pequeñas marcas negras. Pie MOVIMIENTO SIN RUIDO y subtítulo UN ESTUDIO DE EQUILIBRIO / LUZ / ESPACIO. Composición editorial calmada y minimalista.",
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Retrato editorial monocromo de cuerpo entero: mujer de pelo corto con camisa holgada y pantalón ancho sostiene una esfera de cristal a la altura de los ojos. Fondo marfil cálido, grandes letras de contorno apiladas a la izquierda, bloques naranjas detrás y aro naranja a la derecha. Cabecera VELORA / NOTAS DE CAMPO, fecha ABRIL 2027, lema LA FORMA CAMBIA CUANDO MIRAS. VE DESPACIO. OBSERVA MÁS. Retículas finas, índices 04 27 01 y 12 46 59, pequeñas marcas negras. Pie MOVIMIENTO SIN RUIDO y subtítulo UN ESTUDIO DE EQUILIBRIO / LUZ / ESPACIO. Composición editorial calmada y minimalista. Textos en español, fotografías reemplazables y elementos gráficos editables por separado. Conserva la paleta y jerarquía salvo cambios solicitados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación del remix visible y de la referencia. La fotografía es un recurso nuevo; las partes ocultas no se transcriben literalmente."
  },
  {
    "id": "P28",
    "name": "Cine entre la bruma",
    "category": "Fotográficos",
    "title": "LA BRUMA",
    "subtitle": "",
    "color": "#272721",
    "kind": "portrait",
    "image": "/poster-lab/P28.png",
    "reference": true,
    "approved": false,
    "direction": "Cartel de cine independiente sobre papel blanco cálido ligeramente beige. Retrato frontal anónimo en blanco y negro con puntos gruesos de semitono. Una franja horizontal de paisaje portuario con niebla atraviesa los ojos. Arriba créditos de dirección y reparto, laureles y datos de festival. Abajo reseña breve, título LA BRUMA en enormes letras negras y créditos pequeños. Grano de fotocopia, textura de revista antigua, paleta limitada a negro, gris y marfil.",
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Cartel de cine independiente sobre papel blanco cálido ligeramente beige. Retrato frontal anónimo en blanco y negro con puntos gruesos de semitono. Una franja horizontal de paisaje portuario con niebla atraviesa los ojos. Arriba créditos de dirección y reparto, laureles y datos de festival. Abajo reseña breve, título LA BRUMA en enormes letras negras y créditos pequeños. Grano de fotocopia, textura de revista antigua, paleta limitada a negro, gris y marfil. Textos en español, fotografías reemplazables y elementos gráficos editables por separado. Conserva la paleta y jerarquía salvo cambios solicitados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación del remix visible y de la referencia. La fotografía es un recurso nuevo; las partes ocultas no se transcriben literalmente."
  },
  {
    "id": "P29",
    "name": "Desayuno pop",
    "category": "Productos",
    "title": "HAOSHI",
    "subtitle": "",
    "color": "#f4cf39",
    "kind": "product",
    "image": "/poster-lab/P29.png",
    "reference": true,
    "approved": false,
    "direction": "Cartel gastronómico con fondo amarillo yema y tipografía azul ultramar. Marca HAOSHI enorme arriba, Desayunos inclinado en blanco a la derecha. Fotografía central recortada de sándwich de dos tostadas con queso fundido y huevo frito entero, yema visible, brillo natural y textura realista. Lemas COME BIEN y TU MEJOR MAÑANA rodean la comida sin cubrirla. Arcos dibujados y estrellas azules, pie con EST. 2026, SÁNDWICHES DE AUTOR y RECIÉN HECHOS · SERVIDOS CALIENTES.",
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Cartel gastronómico con fondo amarillo yema y tipografía azul ultramar. Marca HAOSHI enorme arriba, Desayunos inclinado en blanco a la derecha. Fotografía central recortada de sándwich de dos tostadas con queso fundido y huevo frito entero, yema visible, brillo natural y textura realista. Lemas COME BIEN y TU MEJOR MAÑANA rodean la comida sin cubrirla. Arcos dibujados y estrellas azules, pie con EST. 2026, SÁNDWICHES DE AUTOR y RECIÉN HECHOS · SERVIDOS CALIENTES. Textos en español, fotografías reemplazables y elementos gráficos editables por separado. Conserva la paleta y jerarquía salvo cambios solicitados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación del remix visible y de la referencia. La fotografía es un recurso nuevo; las partes ocultas no se transcriben literalmente."
  },
  {
    "id": "P30",
    "name": "Cocina de cada día",
    "category": "Productos",
    "title": "Fresco cada día",
    "subtitle": "",
    "color": "#123c2d",
    "kind": "product",
    "image": "/poster-lab/P30.png",
    "reference": true,
    "approved": false,
    "direction": "Cartel de desayuno artesanal: seguir el fondo verde bosque visible de la referencia, título grande crema Fresco cada día, cabecera GRANOS & VERDES · COCINA SIN PRISA. Lema caramelo Las buenas mañanas empiezan aquí. Foto horizontal de tostada de masa madre con aguacate y huevo tierno, yema naranja fluida, plato oscuro y luz suave; esquinas redondeadas. Debajo ingredientes y horario 7:00–11:00. Mantener verde profundo, crema y caramelo, tipografía limpia y espacios generosos.",
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Cartel de desayuno artesanal: seguir el fondo verde bosque visible de la referencia, título grande crema Fresco cada día, cabecera GRANOS & VERDES · COCINA SIN PRISA. Lema caramelo Las buenas mañanas empiezan aquí. Foto horizontal de tostada de masa madre con aguacate y huevo tierno, yema naranja fluida, plato oscuro y luz suave; esquinas redondeadas. Debajo ingredientes y horario 7:00–11:00. Mantener verde profundo, crema y caramelo, tipografía limpia y espacios generosos. Textos en español, fotografías reemplazables y elementos gráficos editables por separado. Conserva la paleta y jerarquía salvo cambios solicitados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación del remix visible y de la referencia. La fotografía es un recurso nuevo; las partes ocultas no se transcriben literalmente."
  },
  {
    "id": "P31",
    "name": "Arquitectura serena",
    "category": "Fotográficos",
    "title": "forma serena",
    "subtitle": "",
    "color": "#337f95",
    "kind": "architecture",
    "image": "/poster-lab/P31.png",
    "reference": true,
    "approved": false,
    "direction": "Página editorial arquitectónica en blanco cálido, negro y acentos azul petróleo. Arriba croquis tenue con ÍNDICE ESPACIOS NOTAS. Collage de casa minimalista de hormigón claro con pared curva, listones negros y luz suave: foto grande a la izquierda marcada 02 y dos detalles a la derecha con 48. Bloques de color pequeños. Debajo UN ESTUDIO DE LUZ, gran título forma serena y dos párrafos sobre materia, luz y habitar despacio. Pie con tres puntos y NOTAS DE CAMPO / EDICIÓN 04. Mucho aire, estética de revista arquitectónica.",
    "remix": "Crea un póster adaptable a 9:16, 4:5 y 1:1. Página editorial arquitectónica en blanco cálido, negro y acentos azul petróleo. Arriba croquis tenue con ÍNDICE ESPACIOS NOTAS. Collage de casa minimalista de hormigón claro con pared curva, listones negros y luz suave: foto grande a la izquierda marcada 02 y dos detalles a la derecha con 48. Bloques de color pequeños. Debajo UN ESTUDIO DE LUZ, gran título forma serena y dos párrafos sobre materia, luz y habitar despacio. Pie con tres puntos y NOTAS DE CAMPO / EDICIÓN 04. Mucho aire, estética de revista arquitectónica. Textos en español, fotografías reemplazables y elementos gráficos editables por separado. Conserva la paleta y jerarquía salvo cambios solicitados.",
    "ratio": "9:16",
    "sourceNote": "Adaptación del remix visible y de la referencia. La fotografía es un recurso nuevo; las partes ocultas no se transcriben literalmente."
  },
  {
    "id": "P32",
    "name": "Bienestar sonoro",
    "category": "Ilustrados",
    "direction": "Crema, rosa y verde; personajes dibujados, taza y notas musicales.",
    "title": "BIENESTAR SONORO",
    "subtitle": "Colección editorial · 2026",
    "color": "#d74c88",
    "kind": "scene",
    "image": "/poster-lab/P32.png",
    "reference": true,
    "approved": false,
    "remix": "Crema, rosa y verde; personajes dibujados, taza y notas musicales. Textos, imágenes y formas editables en 9:16, 4:5 y 1:1. Diseña una pieza editorial cuidada tomando la referencia adjunta como guía de composición. Mantén la paleta descrita y la jerarquía entre titular, imagen protagonista e información secundaria. Usa fotografías o ilustraciones sin letras incrustadas: todos los títulos, códigos, fechas, precios y notas deben permanecer en capas de texto independientes. Conserva cada producto como imagen reemplazable. Reorganiza los elementos para formatos vertical 9:16, retrato 4:5 y cuadrado 1:1, sin estirar las imágenes ni cortar la información. Deja márgenes legibles y conserva el carácter de la referencia.",
    "ratio": "9:16",
    "sourceNote": "Referencia visual aportada por el usuario. Recreación con recursos originales y textos en español."
  },
  {
    "id": "P33",
    "name": "Moda ligera",
    "category": "Productos",
    "direction": "Catálogo blanco con cinco productos independientes y tipografía negra condensada.",
    "title": "VIAJA LIGERO",
    "subtitle": "Colección editorial · 2026",
    "color": "#85b7c7",
    "kind": "product",
    "image": "/poster-lab/P33.png",
    "reference": true,
    "approved": false,
    "remix": "Catálogo blanco con cinco productos independientes y tipografía negra condensada. Textos, imágenes y formas editables en 9:16, 4:5 y 1:1. Diseña una pieza editorial cuidada tomando la referencia adjunta como guía de composición. Mantén la paleta descrita y la jerarquía entre titular, imagen protagonista e información secundaria. Usa fotografías o ilustraciones sin letras incrustadas: todos los títulos, códigos, fechas, precios y notas deben permanecer en capas de texto independientes. Conserva cada producto como imagen reemplazable. Reorganiza los elementos para formatos vertical 9:16, retrato 4:5 y cuadrado 1:1, sin estirar las imágenes ni cortar la información. Deja márgenes legibles y conserva el carácter de la referencia.",
    "ratio": "9:16",
    "sourceNote": "Referencia visual aportada por el usuario. Recreación con recursos originales y textos en español."
  },
  {
    "id": "P34",
    "name": "Taller de formas",
    "category": "Productos",
    "direction": "Artesana, tres piezas de mobiliario y diagonal cobalto sobre arena.",
    "title": "FORMA",
    "subtitle": "Colección editorial · 2026",
    "color": "#265d96",
    "kind": "product",
    "image": "/poster-lab/P34.png",
    "reference": true,
    "approved": false,
    "remix": "Artesana, tres piezas de mobiliario y diagonal cobalto sobre arena. Textos, imágenes y formas editables en 9:16, 4:5 y 1:1. Diseña una pieza editorial cuidada tomando la referencia adjunta como guía de composición. Mantén la paleta descrita y la jerarquía entre titular, imagen protagonista e información secundaria. Usa fotografías o ilustraciones sin letras incrustadas: todos los títulos, códigos, fechas, precios y notas deben permanecer en capas de texto independientes. Conserva cada producto como imagen reemplazable. Reorganiza los elementos para formatos vertical 9:16, retrato 4:5 y cuadrado 1:1, sin estirar las imágenes ni cortar la información. Deja márgenes legibles y conserva el carácter de la referencia.",
    "ratio": "9:16",
    "sourceNote": "Referencia visual aportada por el usuario. Recreación con recursos originales y textos en español."
  },
  {
    "id": "P35",
    "name": "Estudio de color",
    "category": "Productos",
    "direction": "Labial terracota sobre piedra y salvia, titular vertical y ficha editorial.",
    "title": "COLOR / ESTUDIO",
    "subtitle": "Colección editorial · 2026",
    "color": "#af563c",
    "kind": "product",
    "image": "/poster-lab/P35.png",
    "reference": true,
    "approved": false,
    "remix": "Labial terracota sobre piedra y salvia, titular vertical y ficha editorial. Textos, imágenes y formas editables en 9:16, 4:5 y 1:1. Diseña una pieza editorial cuidada tomando la referencia adjunta como guía de composición. Mantén la paleta descrita y la jerarquía entre titular, imagen protagonista e información secundaria. Usa fotografías o ilustraciones sin letras incrustadas: todos los títulos, códigos, fechas, precios y notas deben permanecer en capas de texto independientes. Conserva cada producto como imagen reemplazable. Reorganiza los elementos para formatos vertical 9:16, retrato 4:5 y cuadrado 1:1, sin estirar las imágenes ni cortar la información. Deja márgenes legibles y conserva el carácter de la referencia.",
    "ratio": "9:16",
    "sourceNote": "Referencia visual aportada por el usuario. Recreación con recursos originales y textos en español."
  },
  {
    "id": "P36",
    "name": "Sofá nube",
    "category": "Productos",
    "direction": "Sofá modular crema delante de letras serif negras; acentos azules.",
    "title": "QITA",
    "subtitle": "Colección editorial · 2026",
    "color": "#244bd4",
    "kind": "product",
    "image": "/poster-lab/P36.png",
    "reference": true,
    "approved": false,
    "remix": "Sofá modular crema delante de letras serif negras; acentos azules. Textos, imágenes y formas editables en 9:16, 4:5 y 1:1. Diseña una pieza editorial cuidada tomando la referencia adjunta como guía de composición. Mantén la paleta descrita y la jerarquía entre titular, imagen protagonista e información secundaria. Usa fotografías o ilustraciones sin letras incrustadas: todos los títulos, códigos, fechas, precios y notas deben permanecer en capas de texto independientes. Conserva cada producto como imagen reemplazable. Reorganiza los elementos para formatos vertical 9:16, retrato 4:5 y cuadrado 1:1, sin estirar las imágenes ni cortar la información. Deja márgenes legibles y conserva el carácter de la referencia.",
    "ratio": "9:16",
    "sourceNote": "Referencia visual aportada por el usuario. Recreación con recursos originales y textos en español."
  },
  {
    "id": "P37",
    "name": "Materiales de autor",
    "category": "Productos",
    "direction": "Tres bolsos independientes sobre chocolate oscuro, tipografía marfil.",
    "title": "ESTUDIO DE MATERIA",
    "subtitle": "Colección editorial · 2026",
    "color": "#160d07",
    "kind": "product",
    "image": "/poster-lab/P37.png",
    "reference": true,
    "approved": false,
    "remix": "Tres bolsos independientes sobre chocolate oscuro, tipografía marfil. Textos, imágenes y formas editables en 9:16, 4:5 y 1:1. Diseña una pieza editorial cuidada tomando la referencia adjunta como guía de composición. Mantén la paleta descrita y la jerarquía entre titular, imagen protagonista e información secundaria. Usa fotografías o ilustraciones sin letras incrustadas: todos los títulos, códigos, fechas, precios y notas deben permanecer en capas de texto independientes. Conserva cada producto como imagen reemplazable. Reorganiza los elementos para formatos vertical 9:16, retrato 4:5 y cuadrado 1:1, sin estirar las imágenes ni cortar la información. Deja márgenes legibles y conserva el carácter de la referencia.",
    "ratio": "9:16",
    "sourceNote": "Referencia visual aportada por el usuario. Recreación con recursos originales y textos en español."
  },
  {
    "id": "P38",
    "name": "Fruta fresca",
    "category": "Productos",
    "direction": "Fresa roja protagonista, fondo crema y gran titular negro.",
    "title": "EN SU PUNTO.",
    "subtitle": "Colección editorial · 2026",
    "color": "#b62820",
    "kind": "product",
    "image": "/poster-lab/P38.png",
    "reference": true,
    "approved": false,
    "remix": "Fresa roja protagonista, fondo crema y gran titular negro. Textos, imágenes y formas editables en 9:16, 4:5 y 1:1. Diseña una pieza editorial cuidada tomando la referencia adjunta como guía de composición. Mantén la paleta descrita y la jerarquía entre titular, imagen protagonista e información secundaria. Usa fotografías o ilustraciones sin letras incrustadas: todos los títulos, códigos, fechas, precios y notas deben permanecer en capas de texto independientes. Conserva cada producto como imagen reemplazable. Reorganiza los elementos para formatos vertical 9:16, retrato 4:5 y cuadrado 1:1, sin estirar las imágenes ni cortar la información. Deja márgenes legibles y conserva el carácter de la referencia.",
    "ratio": "9:16",
    "sourceNote": "Referencia visual aportada por el usuario. Recreación con recursos originales y textos en español."
  },
  {
    "id": "P39",
    "name": "Archivo de zapatillas",
    "category": "Productos",
    "direction": "Cinco zapatillas independientes en bandas de color, ficha y código.",
    "title": "MANUAL DE COLOR",
    "subtitle": "Colección editorial · 2026",
    "color": "#a8b9c0",
    "kind": "product",
    "image": "/poster-lab/P39.png",
    "reference": true,
    "approved": false,
    "remix": "Cinco zapatillas independientes en bandas de color, ficha y código. Textos, imágenes y formas editables en 9:16, 4:5 y 1:1. Diseña una pieza editorial cuidada tomando la referencia adjunta como guía de composición. Mantén la paleta descrita y la jerarquía entre titular, imagen protagonista e información secundaria. Usa fotografías o ilustraciones sin letras incrustadas: todos los títulos, códigos, fechas, precios y notas deben permanecer en capas de texto independientes. Conserva cada producto como imagen reemplazable. Reorganiza los elementos para formatos vertical 9:16, retrato 4:5 y cuadrado 1:1, sin estirar las imágenes ni cortar la información. Deja márgenes legibles y conserva el carácter de la referencia.",
    "ratio": "9:16",
    "sourceNote": "Referencia visual aportada por el usuario. Recreación con recursos originales y textos en español."
  },
  {
    "id": "P40",
    "name": "Mochi de temporada",
    "category": "Productos",
    "direction": "Caja de nueve mochis, bloques pastel y banda azul de conservación.",
    "title": "MORI MOCHI",
    "subtitle": "Colección editorial · 2026",
    "color": "#0a35a4",
    "kind": "product",
    "image": "/poster-lab/P40.png",
    "reference": true,
    "approved": false,
    "remix": "Caja de nueve mochis, bloques pastel y banda azul de conservación. Textos, imágenes y formas editables en 9:16, 4:5 y 1:1. Diseña una pieza editorial cuidada tomando la referencia adjunta como guía de composición. Mantén la paleta descrita y la jerarquía entre titular, imagen protagonista e información secundaria. Usa fotografías o ilustraciones sin letras incrustadas: todos los títulos, códigos, fechas, precios y notas deben permanecer en capas de texto independientes. Conserva cada producto como imagen reemplazable. Reorganiza los elementos para formatos vertical 9:16, retrato 4:5 y cuadrado 1:1, sin estirar las imágenes ni cortar la información. Deja márgenes legibles y conserva el carácter de la referencia.",
    "ratio": "9:16",
    "sourceNote": "Referencia visual aportada por el usuario. Recreación con recursos originales y textos en español."
  }
];
