import { useEffect,useRef,useState } from 'react';
import { replaceLayerImage,formatLayers,formatHeights,loadFormat,type PosterFormat,exportSvg,initialLayers,layerKey,layerMarkup,layerTransform,localPortraits,templateNames,loadLayers,type Layer,type LayerTemplate } from './layers';
import './layer-editor.css';
export default function LayerEditor({onBack,template="P03"}:{onBack:()=>void;template?:LayerTemplate}){
 const [format,setFormat]=useState<PosterFormat>(()=>loadFormat(template));
 const height=formatHeights[format];
 const [layers,setLayers]=useState(()=>loadLayers(template,loadFormat(template))),[selected,select]=useState('title'),[past,setPast]=useState<Layer[][]>([]),[future,setFuture]=useState<Layer[][]>([]),[status,setStatus]=useState('');
 const svg=useRef<SVGSVGElement>(null),drag=useRef<{x:number;y:number;layer:Layer;before:Layer[]}|null>(null);
 const current=layers.find(l=>l.id===selected);
 useEffect(()=>{try{localStorage.setItem(layerKey(template,format),JSON.stringify(layers));localStorage.setItem(`poster-lab-${template}-format`,format);}catch{setStatus('No se pudo guardar en el navegador. Descarga el SVG para conservar el diseño.');}},[layers,template,format]);
 function changeFormat(next:PosterFormat){if(next===format)return;let cached:Layer[]|undefined;try{if(localStorage.getItem(layerKey(template,next)))cached=loadLayers(template,next);}catch{}setLayers(formatLayers(layers,format,next,cached,template));setFormat(next);setPast([]);setFuture([]);setStatus('Formato actualizado. Textos y colores conservados; el historial empieza en este formato.');}
 function commit(next:Layer[]){setPast(p=>[...p.slice(-79),layers]);setFuture([]);setLayers(next);}
 function patch(change:Partial<Layer>){commit(layers.map(l=>l.id===selected?{...l,...change}:l));}
 function undo(){if(!past.length)return;setFuture(f=>[layers,...f]);setLayers(past[past.length-1]);setPast(p=>p.slice(0,-1));}
 function redo(){if(!future.length)return;setPast(p=>[...p,layers]);setLayers(future[0]);setFuture(f=>f.slice(1));}
 function add(){const id=crypto.randomUUID();commit([...layers,{...initialLayers()[2],id,name:'Nuevo texto',text:'TU TEXTO',x:100,y:Math.round(height*.6),size:40}]);select(id);}
 function moveOrder(delta:number){const i=layers.findIndex(l=>l.id===selected),j=i+delta;if(i<0||j<0||j>=layers.length)return;const next=[...layers];[next[i],next[j]]=[next[j],next[i]];commit(next);}
 function point(e:React.PointerEvent){const matrix=svg.current?.getScreenCTM();if(!matrix)return {x:0,y:0};return new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());}
 function start(e:React.PointerEvent,l:Layer){select(l.id);if(l.id==='paper')return;e.preventDefault();const p=point(e);drag.current={...p,layer:l,before:layers};e.currentTarget.setPointerCapture(e.pointerId);}
 function moving(e:React.PointerEvent){const d=drag.current;if(!d)return;const p=point(e);setLayers(d.before.map(l=>l.id===d.layer.id?{...l,x:Math.round(d.layer.x+p.x-d.x),y:Math.round(d.layer.y+p.y-d.y)}:l));}
 function finish(){const d=drag.current;if(!d)return;drag.current=null;if(JSON.stringify(layers)!==JSON.stringify(d.before)){setPast(p=>[...p.slice(-79),d.before]);setFuture([]);}}
 function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function outputSvg(){
 const embedded=await Promise.all(layers.map(async l=>{
  if(!l.src||!localPortraits.includes(l.src||''))return l;
  const response=await fetch(l.src);if(!response.ok)throw Error('Foto no disponible');
  const src=await dataUrl(await response.blob());return {...l,src};
 }));return exportSvg(embedded,format);
 }
 function dataUrl(blob:Blob):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob);});}
 async function uploadPhoto(file?:File){if(!file)return;const target=selected;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){setStatus('Usa una foto JPG, PNG o WebP de hasta 2 MB.');return;}try{const src=await dataUrl(file);const probe=new Image();probe.src=src;await probe.decode();commit(replaceLayerImage(layers,target,src));setStatus(current?.sliceIndex!==undefined?'Retrato reemplazado en los cuatro fragmentos.':'Foto reemplazada. Ajusta el zoom y el encuadre.');}catch{setStatus('No se pudo abrir esa foto.');}}
 async function svgDownload(){try{download(new Blob([await outputSvg()],{type:'image/svg+xml'}),`poster-${template}-${format.replace(':','x')}-editable.svg`);setStatus('SVG descargado con sus capas editables.');}catch{setStatus('No se pudo descargar el SVG. Comprueba la foto.');}}
 async function png(){setStatus('Preparando PNG…');let url='';try{url=URL.createObjectURL(new Blob([await outputSvg()],{type:'image/svg+xml'}));const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)throw Error();ctx.drawImage(img,0,0);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/png'));if(!blob)throw Error();download(blob,`poster-${template}-1080x${height}.png`);setStatus(`PNG descargado en 1080 × ${height}.`);}catch{setStatus('No se pudo crear el PNG. Puedes descargar el SVG.');}finally{URL.revokeObjectURL(url);}}
 return <div className="le"><header><button onClick={onBack}>← Volver al catálogo</button><span>POSTER LAB / {template} · {templateNames[template].toUpperCase()}</span></header>
 <div className="le-heading"><h1>Tu diseño, pieza por pieza.</h1><p>Selecciona una capa en el póster o en la lista. Edita, arrastra o borra. Formato {format} · guardado en este navegador.</p></div>
 {<label className="le-format">Formato<select aria-label="Formato" value={format} onChange={e=>changeFormat(e.target.value as PosterFormat)}><option value="9:16">9:16 · 1080 × 1920</option><option value="4:5">4:5 · 1080 × 1350</option><option value="1:1">1:1 · 1080 × 1080</option></select><span>Textos y colores compartidos. Posiciones guardadas por formato.</span></label>}
 <nav className="le-toolbar" aria-label="Herramientas del diseño"><button onClick={undo} disabled={!past.length}>Deshacer</button><button onClick={redo} disabled={!future.length}>Rehacer</button><button onClick={add}>Añadir texto</button><button onClick={()=>commit(formatLayers(initialLayers(template),'9:16',format,undefined,template))}>Restaurar plantilla</button><button onClick={svgDownload}>Descargar SVG</button><button className="le-primary" onClick={png}>Descargar PNG</button></nav>
 <div className="le-layout"><aside><h2>Capas · {layers.length}</h2><p>Las de arriba se dibujan delante.</p><div className="le-layer-list">{[...layers].reverse().map(l=><button key={l.id} aria-pressed={selected===l.id} onClick={()=>select(l.id)}>{l.type==='text'?'T':l.type==='image'?'▧':'◇'} {l.name}</button>)}</div></aside>
 <main className="le-stage"><svg ref={svg} overflow="hidden" viewBox={`0 0 1080 ${height}`} style={{aspectRatio:`1080 / ${height}`}} role="group" aria-label={`Póster editable ${format}`} onPointerMove={moving} onPointerUp={finish} onPointerCancel={finish}>
 {layers.map(l=><g key={l.id} transform={layerTransform(l)} role="button" aria-label={`Seleccionar ${l.name}`} tabIndex={0} onClick={()=>select(l.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')select(l.id);}} onPointerDown={e=>start(e,l)} style={{cursor:l.id==='paper'?'pointer':'move'}}>
 {l.imageFill||l.type==='fish'||l.type==='glasses'||l.type==='image'||l.type==='ellipse'||l.type==='bolt'||l.type==='wave'||l.type==='arc'||l.type==='semicircle'||l.type==='ribbon'||l.type==='paperCut'?<g dangerouslySetInnerHTML={{__html:layerMarkup({...l,rotation:0})}}/>:l.type==='text'?<text style={{textShadow:l.shadowColor?`6px 6px 0 ${l.shadowColor}`:undefined}} fill={l.outline?'none':l.color} stroke={l.outline?l.color:l.textStroke} strokeWidth={1.8} fontFamily={l.font} fontSize={l.size} fontWeight={l.bold?700:400}>{l.text.split('\n').map((t,i)=><tspan key={i} x={l.x} y={l.y+i*l.size*1.15}>{t||' '}</tspan>)}</text>:l.type==='triangle'?<polygon fill={l.color} points={`${l.x},${l.y} ${l.x+l.w},${l.y} ${l.x+l.w},${l.y+l.h}`}/>:<rect x={l.x} y={l.y} width={l.w} height={l.h} fill={l.color}/>}
 </g>)}
 {current&&<rect transform={layerTransform(current)} pointerEvents="none" x={current.x-5} y={current.type==='text'?current.y-current.size:current.y-5} width={current.type==='text'?Math.max(current.size,...current.text.split('\n').map(t=>t.length*current.size*.64)):current.w+10} height={current.type==='text'?current.text.split('\n').length*current.size*1.15:current.h+10} fill="none" stroke="#8756da" strokeWidth="3" strokeDasharray="10 7"/>}
 </svg><p>Reconstrucción editable del estilo {templateNames[template]}. El borde violeta no se descarga. El texto no se ajusta automáticamente: usa saltos de línea o cambia su tamaño.</p></main>
 <aside className="le-properties"><h2>{current?'Editar capa':'Selecciona una capa'}</h2>{current&&<>
 <label>Nombre de la capa<input value={current.name} onChange={e=>patch({name:e.target.value})}/></label>
 {current.type==='text'&&<><label>Texto<textarea rows={5} value={current.text} onChange={e=>patch({text:e.target.value})}/></label><label>Tipografía<select value={current.font} onChange={e=>patch({font:e.target.value})}><option>Arial</option><option>Impact</option><option>Georgia</option><option>Times New Roman</option><option>Courier New</option><option value="cursive">Manuscrita</option></select></label><label>Tamaño<input type="number" min={8} max={600} value={current.size} onChange={e=>patch({size:Math.max(8,Math.min(600,Number(e.target.value)))})}/></label><label className="le-check"><input type="checkbox" checked={!!current.outline} onChange={e=>patch({outline:e.target.checked})}/>Solo contorno</label><label className="le-check"><input type="checkbox" checked={current.bold} onChange={e=>patch({bold:e.target.checked})}/>Negrita</label></>}
 {current.type==='text'&&current.src&&<label className="le-check"><input type="checkbox" checked={!!current.imageFill} onChange={e=>patch({imageFill:e.target.checked})}/>Fotografía dentro del texto</label>}{current.type==='image'&&<><label>Reemplazar foto<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadPhoto(e.target.files?.[0])}/></label><p>La imagen inicial está preparada para este estilo. Puedes sustituirla por otra foto. Para una silueta sin fondo usa un PNG transparente; la subida no elimina el fondo automáticamente.</p>{current.sliceIndex===undefined&&current.spriteIndex===undefined&&<><label>Recorte<select value={current.crop||'ellipse'} onChange={e=>patch({crop:e.target.value as Layer['crop']})}><option value="none">Silueta completa</option><option value="ellipse">Óvalo</option><option value="bolt">Rayo</option><option value="arch">Arco</option><option value="rounded">Esquinas redondas</option></select></label><label>Ajuste de imagen<select value={current.fit||'contain'} onChange={e=>patch({fit:e.target.value as 'cover'|'contain'})}><option value="contain">Mostrar completa</option><option value="cover">Llenar el encuadre</option></select></label></>}<label>Zoom de la foto<input type="range" min="0.5" max="4" step="0.05" value={current.zoom||1} onChange={e=>patch({zoom:Number(e.target.value)})}/></label><div className="le-pair">{(['offsetX','offsetY'] as const).map(k=><label key={k}>Encuadre {k==='offsetX'?'X':'Y'}<input type="number" value={current[k]||0} onChange={e=>patch({[k]:Number(e.target.value)})}/></label>)}</div>{current.sliceIndex!==undefined?<><p>La foto se reemplaza en los cuatro fragmentos. Cada franja conserva su posición y se puede borrar por separado.</p><label className="le-check"><input type="checkbox" checked={!!current.sepia} onChange={e=>patch({sepia:e.target.checked})}/>Tono sepia</label></>:current.spriteIndex===undefined?<label className="le-check"><input type="checkbox" checked={!!current.mono} onChange={e=>patch({mono:e.target.checked})}/>Blanco y negro</label>:null}</>}
 {current.type==='text'&&current.shadowColor&&<label>Color de sombra<input type="color" value={current.shadowColor} onChange={e=>patch({shadowColor:e.target.value})}/></label>}
 <label>Color<input type="color" value={current.color} onChange={e=>patch({color:e.target.value})}/></label>
 <div className="le-pair">{(['x','y'] as const).map(k=><label key={k}>Posición {k.toUpperCase()}<input type="number" value={current[k]} onChange={e=>patch({[k]:Number(e.target.value)})}/></label>)}</div>
 {current.type!=='text'&&<div className="le-pair">{(['w','h'] as const).map(k=><label key={k}>{k==='w'?'Ancho':'Alto'}<input type="number" min={1} value={current[k]} onChange={e=>patch({[k]:Math.max(1,Number(e.target.value))})}/></label>)}</div>}
 <label>Rotación (grados)<input type="number" min={-180} max={180} value={current.rotation||0} onChange={e=>patch({rotation:Math.max(-180,Math.min(180,Number(e.target.value)))})}/></label>
 <button onClick={()=>moveOrder(1)}>Traer una capa adelante</button><button onClick={()=>moveOrder(-1)}>Enviar una capa atrás</button><button className="le-delete" onClick={()=>{commit(layers.filter(l=>l.id!==selected));select('');}}>Borrar capa</button>
 </>}</aside></div><p role="status">{status}</p></div>;
}
