import { useState } from 'react';
import { Plus, Search, Copy, Trash2, Pencil, Download, Upload } from 'lucide-react';
import { BASE, CostEntry, validLibrary } from './library';
import ExcelImport from './ExcelImport';
import { mergeEntries } from './importModel';
import { money, number } from './model';
type Props = { entries: CostEntry[]; onChange: (entries: CostEntry[]) => void; onAdd: (entry: CostEntry) => void; saved: boolean; };
export default function Library({entries,onChange,onAdd,saved}:Props) {
 const [importing,setImporting]=useState(false);
 const [limit,setLimit]=useState(24);
 const [origin,setOrigin]=useState('');
 const [source,setSource]=useState<'mine'|'base'>('mine');
 const [query,setQuery]=useState(''); const [category,setCategory]=useState('');
 const [draft,setDraft]=useState<CostEntry|null>(null); const [notice,setNotice]=useState('');
 const list=source==='mine'?entries:BASE;
 const categories=[...new Set(list.filter(e=>!origin||e.source===origin).map(e=>e.category))];
 const visible=list.filter(e=>(!origin || e.source===origin) && (!category || e.category===category) && `${e.description} ${e.unit} ${e.category} ${e.source||''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,entries},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='mis-costos.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const restore=async(file?:File)=>{if(!file)return;try{if(file.size>2_000_000)throw Error();const data=JSON.parse(await file.text());if(data.version!==1 || !validLibrary(data.entries))throw Error();if(!window.confirm('Este respaldo reemplazará Mis costos. El presupuesto no se modificará. ¿Continuar?'))return;onChange(data.entries);setNotice('Biblioteca restaurada.');}catch{setNotice('Archivo no válido. Usa un respaldo JSON de Mis costos.');}};
 return <section className="cost-library">
 <div className="cost-toolbar"><div><span className="cost-eyebrow">TU BIBLIOTECA</span><h2>Precios que puedes volver a usar.</h2><p className="cost-help">Añade una copia al presupuesto y ajusta allí la cantidad.</p></div><button className="cost-primary" onClick={()=>{setSource('mine');setDraft({id:crypto.randomUUID(),description:'',unit:'m²',cost:0,markup:25,category:'Mis rubros'});}}><Plus size={16}/> Crear rubro</button></div>
 <div className="cost-library-bar"><div className="cost-tabs"><button aria-pressed={source==='mine'} onClick={()=>{setSource('mine');setCategory('');setOrigin('');}}>Mis costos ({entries.length})</button><button aria-pressed={source==='base'} onClick={()=>{setSource('base');setCategory('');setOrigin('');}}>Base ArquiRender ({BASE.length})</button></div><div className="cost-actions"><button className="cost-primary" onClick={()=>setImporting(true)}><Upload size={15}/> Importar Excel</button><button onClick={download}><Download size={15}/> Respaldar biblioteca</button><label className="cost-restore"><Upload size={15}/> Abrir biblioteca<input aria-label="Abrir biblioteca" type="file" accept=".json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value='';}}/></label></div></div>
 <p className="cost-help">{source==='base'?'Rubros de tus cuatro archivos originales. Revisa alcance y vigencia; no son precios actualizados automáticamente. Copia los que necesites a Mis costos.':'Crea tus rubros, importa tu Excel o copia los de la base. Editarla no cambia los presupuestos existentes.'}</p>
 <p className="cost-save" role="status">{saved?'Mis costos se guarda en este navegador.':'No se pudo guardar la biblioteca. Descarga un respaldo antes de salir.'}</p>
 {importing && <ExcelImport entries={entries} onClose={()=>setImporting(false)} onImport={(next,message)=>{onChange(next);setImporting(false);setSource('mine');setCategory('');setOrigin('');setQuery('');setNotice(message);}}/>}
 {notice && <p className="cost-notice" role="status">{notice}</p>}
 {draft && <form className="cost-library-form" onSubmit={e=>{e.preventDefault();if(!draft.description.trim()||!draft.unit.trim())return;onChange([...entries.filter(v=>v.id!==draft.id),{...draft,description:draft.description.trim(),unit:draft.unit.trim(),category:draft.category.trim()||'Mis rubros'}]);setDraft(null);setNotice('Rubro guardado en Mis costos.');}}>
 <h3>{entries.some(e=>e.id===draft.id)?'Editar rubro':'Nuevo rubro'}</h3><label>Descripción del rubro<input required value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Unidad del rubro<input required value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})}/></label><label>Categoría<input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>Costo unitario USD<input type="number" min="0" max="1000000000" step="0.01" value={draft.cost} onChange={e=>setDraft({...draft,cost:number(e.target.valueAsNumber)})}/></label><label>Utilidad del rubro %<input type="number" min="0" max="1000000000" step="0.01" value={draft.markup} onChange={e=>setDraft({...draft,markup:number(e.target.valueAsNumber)})}/></label><div className="cost-actions"><button type="submit" className="cost-primary">Guardar rubro</button><button type="button" onClick={()=>setDraft(null)}>Cancelar</button></div></form>}
 <div className="cost-library-search"><label><Search size={16}/><input aria-label="Buscar rubros" placeholder="Buscar por descripción, unidad o categoría…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filtrar origen" value={origin} onChange={e=>{setOrigin(e.target.value);setCategory('');}}><option value="">Todos los orígenes</option>{[...new Set(list.map(e=>e.source).filter(Boolean))].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filtrar categoría" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas las categorías</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
 {source==='base' && <div className="cost-toolbar"><p className="cost-help">{visible.length} rubros encontrados</p><button onClick={()=>{const merged=mergeEntries(entries,visible);if(merged.entries.length>5000){setNotice('Máximo 5.000 rubros en Mis costos.');return;}onChange(merged.entries);setNotice(`${merged.added} rubros copiados; ${merged.duplicates} repetidos omitidos.`);}}>Copiar selección a Mis costos</button></div>}
 <div className="cost-library-grid">{visible.slice(0,limit).map(e=><article key={e.id}><span className="cost-eyebrow">{e.category}</span><h3>{e.description.length>140?`${e.description.slice(0,140)}…`:e.description}</h3>{e.description.length>140&&<details><summary>Ver descripción completa</summary><p className="cost-help">{e.description}</p></details>}<p><strong>{money(e.cost)}</strong> / {e.unit}</p><small>Utilidad sobre costo: {e.markup}%</small>{e.source && <details><summary>{e.source}</summary><p className="cost-help">{e.sourceFile} · {e.sourceSheet} · fila {e.sourceRow}</p><p className="cost-help">{e.note}</p></details>}<div className="cost-actions"><button className="cost-primary" onClick={()=>{onAdd(e);setNotice(`«${e.description}» añadido al presupuesto con cantidad 1.`);}}><Plus size={15}/> Añadir al presupuesto</button>{source==='base'?<button onClick={()=>{const merged=mergeEntries(entries,[e]);onChange(merged.entries);setNotice(merged.added?'Copia creada en Mis costos.':'Ya existe un rubro con esa descripción, unidad y categoría.');}}><Copy size={15}/> Copiar a Mis costos</button>:<><button aria-label={`Editar ${e.description}`} onClick={()=>setDraft({...e})}><Pencil size={15}/></button><button aria-label={`Eliminar ${e.description}`} onClick={()=>{if(window.confirm(`¿Eliminar «${e.description}» de Mis costos? Las partidas del presupuesto se conservan.`)){onChange(entries.filter(v=>v.id!==e.id));setNotice('Rubro eliminado de la biblioteca.');}}}><Trash2 size={15}/></button></>}</div></article>)}</div>
 {visible.length>limit && <button className="cost-add" onClick={()=>setLimit(n=>n+24)}>Mostrar más ({visible.length-limit} restantes)</button>}
 {!visible.length && <div className="cost-empty"><h3>{list.length?'No hay coincidencias':'Tu biblioteca está lista para empezar.'}</h3><p>{list.length?'Prueba otra búsqueda o categoría.':'Crea tu primer rubro o abre la base para copiar uno.'}</p></div>}
 </section>;
}
