import { useState } from 'react';
import { BASE, CostEntry } from './library';
import { Item } from './model';
import { acceptedItem, analyzeCosts, Result } from './analysis';
export default function CostAnalysis({entries,onAdd}:{entries:CostEntry[];onAdd:(item:Item)=>void}) {
 const [files,setFiles]=useState<File[]>([]),[scope,setScope]=useState(''),[measures,setMeasures]=useState(''),[kind,setKind]=useState('Reforma'),[source,setSource]=useState('mine');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<Result|null>(null),[snapshot,setSnapshot]=useState<CostEntry[]>([]),[done,setDone]=useState<number[]>([]);
 const library=source==='mine'?entries:BASE.filter(e=>e.source===source);
 async function run(){setBusy(true);setMessage('Preparando archivos…');setResult(null);setDone([]);const selected=library.map(e=>({...e}));setSnapshot(selected);try{setResult(await analyzeCosts(files,`Tipo de intervención: ${kind}\nQué presupuestar y alcance: ${scope}\nMedidas conocidas: ${measures||'No proporcionadas'}`,selected,setMessage));setMessage('Revisa cada propuesta antes de añadirla. Los costos corresponden a la biblioteca seleccionada al analizar.');}catch(e){setMessage(e instanceof Error?e.message:'No se pudo analizar.');}finally{setBusy(false);}}
 return <section className="cost-work cost-analysis"><h2>Del render a tus rubros</h2><p>Sube imágenes o un PDF del mismo proyecto. La IA propone partidas; tú revisas y decides.</p>
 <fieldset disabled={busy}><div className="cost-meta"><label>Archivos del proyecto<input type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>{setFiles(Array.from(e.target.files||[]));setResult(null);}}/></label><label>Intervención<select value={kind} onChange={e=>setKind(e.target.value)}>{['Obra nueva','Reforma','Adecuación','Ampliación','Otro'].map(v=><option key={v}>{v}</option>)}</select></label><label>Biblioteca para este análisis<select value={source} onChange={e=>setSource(e.target.value)}><option value="mine">Mis costos ({entries.length})</option>{[...new Set(BASE.map(e=>e.source))].map(s=><option key={s} value={s}>{s}</option>)}</select></label></div>
 <label>¿Qué deseas presupuestar? Alcance y exclusiones<textarea maxLength={3500} value={scope} onChange={e=>setScope(e.target.value)} placeholder="Ej.: acabados nuevos del local; conservar piso y mobiliario existente."/></label><label>Medidas conocidas y aclaraciones<textarea maxLength={1800} value={measures} onChange={e=>setMeasures(e.target.value)} placeholder="Ej.: ambiente de 4,20 × 6,50 m. Las fotos muestran el mismo espacio desde distintos ángulos."/></label>
 <p className="cost-help">Hasta 12 imágenes/páginas en total · 20 MB por archivo. Se envían a OpenAI imágenes reducidas, el alcance y las descripciones de los rubros; no tus precios. Las cotas ilegibles quedan pendientes. Comparte el límite de 30 análisis diarios con Presentaciones.</p>
 <button className="cost-primary" disabled={!files.length||files.length>12||!scope.trim()||!library.length||library.length>1000} onClick={()=>void run()}>{busy?'Analizando…':'Analizar proyecto'}</button>{!library.length&&<p>Añade rubros a Mis costos o selecciona una biblioteca base.</p>}</fieldset>
 <p role="status">{message}</p>
 {result&&<><h3>Propuestas para revisar ({result.items.length})</h3>{result.items.length===0&&<p>No se identificaron partidas justificables. Revisa las preguntas.</p>}{result.items.map((p,index)=> <article className="cost-ai-row" key={index}><strong>{p.element}</strong><span>{p.status}</span><p>{p.source}</p><p>{p.evidence}</p><p>{p.observation}</p><fieldset disabled={done.includes(index)}><label>Rubro de biblioteca<select value={p.rubricId||''} onChange={e=>{const entry=snapshot.find(r=>r.id===e.target.value);setResult({...result,items:result.items.map((r,i)=>i===index?{...r,rubricId:entry?.id||null,unit:entry?.unit||'',status:'PENDIENTE'}:r)});}}><option value="">Sin coincidencia · pendiente</option>{snapshot.map(e=><option key={e.id} value={e.id}>{e.description} ({e.unit})</option>)}</select></label><label>Cantidad · {p.unit||'unidad pendiente'}<input type="number" min="0.0001" max="1000000000" step="any" value={p.quantity??''} onChange={e=>setResult({...result,items:result.items.map((r,i)=>i===index?{...r,quantity:Number.isFinite(e.target.valueAsNumber)?e.target.valueAsNumber:null,status:'PENDIENTE'}:r)})}/></label>
 {!['CONFIRMADO','ESTIMADO'].includes(p.status)&&<label><input type="checkbox" checked={false} disabled={!p.rubricId||!p.quantity||p.quantity<=0} onChange={()=>setResult({...result,items:result.items.map((r,i)=>i===index?{...r,status:'CONFIRMADO',observation:r.observation+' · Rubro y cantidad confirmados por el usuario.'}:r)})}/> He comprobado el alcance, el rubro y la cantidad</label>}
 <button disabled={!p.rubricId||!p.quantity||!['CONFIRMADO','ESTIMADO'].includes(p.status)} onClick={()=>{try{onAdd(acceptedItem(p,snapshot));setDone(v=>[...v,index]);}catch(e){setMessage((e as Error).message);}}}>{done.includes(index)?'Revisada':'Aceptar y añadir'}</button> <button onClick={()=>setDone(v=>[...v,index])}>Descartar</button></fieldset></article>)}
 <h3>Información necesaria para continuar</h3>{result.questions.map((q,i)=><p key={i}>{q}</p>)}<p>Para resolver pendientes, completa los datos arriba y vuelve a analizar. Las partidas ya añadidas permanecen en el presupuesto: comprueba que no las añadas otra vez.</p></>}
 </section>;
}
