import { useEffect, useState } from 'react';
import { analysisLibrary, CostEntry } from './library';
import Attachments from './Attachments';
import { Item } from './model';
import RenderPicker, { SavedRender } from './RenderPicker';
import { supabase } from '@/integrations/supabase/client';
import { draftItems, analyzeCosts, Result } from './analysis';
export default function CostAnalysis({entries,onGenerate,projectType="local"}:{entries:CostEntry[];onGenerate:(items:Item[])=>void;projectType?:"local"|"casa"}) {
 const [files,setFiles]=useState<File[]>([]),[scope,setScope]=useState(''),[measures,setMeasures]=useState(''),[kind,setKind]=useState('Reforma'),[source,setSource]=useState<'combined'|'personal'>('combined');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<Result|null>(null);
 const [renders,setRenders]=useState<SavedRender[]>([]);
 useEffect(()=>{let userId:string|undefined;const {data}=supabase.auth.onAuthStateChange((_event,session)=>{if(userId!==session?.user.id){setRenders([]);setResult(null);}userId=session?.user.id;});return()=>data.subscription.unsubscribe();},[]);
 const library=analysisLibrary(entries,source);
 async function run(){setBusy(true);setMessage('Preparando archivos…');setResult(null);const selected=library.map(e=>({...e}));try{const proposal=await analyzeCosts(files,`Tipo de proyecto: ${projectType==='casa'?'Casa / vivienda':'Local comercial / interiores'}\nBiblioteca seleccionada: ${source}\nTipo de intervención: ${kind}\nQué presupuestar y alcance: ${scope.trim()||'Análisis preliminar de los elementos visibles. Generar cotización preliminar de todos los elementos identificables, estimando cantidades cuando haya una referencia visual razonable. Documentar supuestos, evitar duplicados y no suponer instalaciones ocultas.'}\nMedidas conocidas: ${measures||'No proporcionadas'}`,selected,setMessage,renders);setResult(proposal);if(!proposal.items.length){setMessage('No se identificaron partidas. El presupuesto anterior permanece intacto.');return;}onGenerate(draftItems(proposal,selected));setMessage('Cotización preliminar generada en la tabla. Edita cantidades, costos y utilidad directamente. Los supuestos están en Revisión técnica.');}catch(e){setMessage(e instanceof Error?e.message:'No se pudo analizar.');}finally{setBusy(false);}}
 return <section className="cost-work cost-analysis"><h2>Del render a tus rubros</h2><p>Sube imágenes o un PDF del mismo proyecto. La IA genera tu cotización preliminar; después ajustas cantidades y precios en la tabla.</p>
 <fieldset disabled={busy}><RenderPicker selected={renders} limit={Math.max(0,12-files.length)} onChange={items=>{setRenders(items);setResult(null);}}/><div className="cost-meta"><label>Archivos del proyecto<input type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>{const added=Array.from(e.target.files||[]);setFiles(old=>[...old,...added.filter(f=>!old.some(o=>o.name===f.name&&o.size===f.size&&o.lastModified===f.lastModified))]);e.target.value='';setResult(null);}}/></label><label>Intervención<select value={kind} onChange={e=>setKind(e.target.value)}>{['Obra nueva','Reforma','Adecuación','Ampliación','Otro'].map(v=><option key={v}>{v}</option>)}</select></label><label>Precios para la cotización<select value={source} onChange={e=>setSource(e.target.value as 'combined'|'personal')}><option value="combined">Base ArquiRender + mis precios</option><option value="personal">Solo mis precios ({entries.length})</option></select></label></div>
 <p>{renders.length} renders + {files.length} archivos adjuntos · {projectType==='casa'?'Casa / vivienda':'Local comercial / interiores'} · {library.length} rubros en la biblioteca seleccionada</p>
 <Attachments files={files} onRemove={index=>{setFiles(old=>old.filter((_,i)=>i!==index));setResult(null);}}/>
 <label>¿Qué deseas presupuestar? Alcance y exclusiones (opcional)<textarea maxLength={3500} value={scope} onChange={e=>setScope(e.target.value)} placeholder="Ej.: acabados nuevos del local; conservar piso y mobiliario existente."/></label><label>Medidas conocidas y aclaraciones<textarea maxLength={1800} value={measures} onChange={e=>setMeasures(e.target.value)} placeholder="Ej.: ambiente de 4,20 × 6,50 m. Las fotos muestran el mismo espacio desde distintos ángulos."/></label>
 <p className="cost-help">Hasta 12 imágenes/páginas en total · 20 MB por archivo. Se envían a OpenAI imágenes reducidas, el alcance y las descripciones de los rubros, sin enviar tus precios. Las cotas ilegibles quedan pendientes. Comparte el límite de 30 análisis diarios con Presentaciones.</p>
 {!scope.trim()&&<p className="cost-help">Generaremos una primera cotización con estimaciones identificadas. Puedes corregirla directamente en la tabla.</p>}
 {!(files.length+renders.length)&&<p>Selecciona al menos un render o adjunta un archivo.</p>}{files.length+renders.length>12&&<p role="alert">Hay más de 12 adjuntos. Quita algunos para continuar.</p>}{library.length>1000&&<p role="alert">Selecciona una biblioteca con hasta 1.000 rubros.</p>}
 <button className="cost-primary" disabled={!(files.length+renders.length)||files.length+renders.length>12||!library.length||library.length>1000} onClick={()=>void run()}>{busy?'Analizando…':'Generar cotización'}</button>{!library.length&&<p>Añade rubros a Mis costos o selecciona una biblioteca base.</p>}</fieldset>
 <p role="status">{message}</p>
 {result&&<><h3>{result.items.length} partidas identificadas</h3><p>La cotización está debajo. Las partidas sin referencia suficiente permanecen visibles como «Por definir» y no se incluyen en el total parcial.</p>{result.questions.length>0&&<details><summary>Información para afinar la cotización ({result.questions.length})</summary>{result.questions.map((q,i)=><p key={i}>{q}</p>)}</details>}</>}
 </section>;
}
