import { ChangeEvent, FormEvent, Fragment, useMemo, useState } from 'react';
import { ArrowLeft, CalendarDays, Check, ClipboardList, Download, HardHat, ImagePlus, Plus, ShieldAlert, Trash2, Upload } from 'lucide-react';
import { readDocument, useDocument } from '../costos/storage';
import { totals, validBudget } from '../costos/model';
import { downloadScheduleTemplate, importSchedule } from './excel';
import { clamp, emptyDocument, finances, money, newWork, riskLevel, riskScore, taskStatus, today, uid, validWorksDocument, Work, WorkLog, WorkMovement, WorkRisk, WorkTask, WorksDocument } from './model';
import './obras.css';

type DetailTab = 'summary' | 'schedule' | 'log' | 'team' | 'risks' | 'money';
const statusLabel = { planning: 'Planificación', active: 'En ejecución', paused: 'Pausada', completed: 'Completada' } as const;
const taskLabel = { planned: 'Por iniciar', active: 'En curso', late: 'Atrasada', completed: 'Terminada' } as const;
const number = (value: string) => clamp(Number(value));
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="works-field"><span>{label}</span>{children}</label>;

function percentage(work: Work) {
  if (!work.tasks.length) return 0;
  const days = (task: WorkTask) => Math.max(1, Math.round((Date.parse(task.end) - Date.parse(task.start)) / 86_400_000) + 1);
  const total = work.tasks.reduce((sum, task) => sum + days(task), 0);
  return Math.round(work.tasks.reduce((sum, task) => sum + clamp(task.progress, 100) * days(task), 0) / total);
}

async function evidence(file?: File) {
  if (!file) return '';
  if (!file.type.startsWith('image/') || file.size > 15_000_000) throw new Error('Selecciona una imagen de hasta 15 MB.');
  const source = URL.createObjectURL(file);
  try {
    const image = new Image();
    await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error('No se pudo abrir la imagen.')); image.src = source; });
    const scale = Math.min(1, 1200 / Math.max(image.width, image.height));
    const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale));
    canvas.getContext('2d')?.drawImage(image, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL('image/jpeg', .72);
  } finally { URL.revokeObjectURL(source); }
}

export default function Obras() {
  const [document, setDocument, saved, ready] = useDocument<WorksDocument>('arquirender-works-v1', emptyDocument, validWorksDocument);
  const [rootView, setRootView] = useState<'portfolio' | 'timeline'>('portfolio');
  const [tab, setTab] = useState<DetailTab>('summary');
  const [creating, setCreating] = useState(false);
  const [notice, setNotice] = useState('');
  const selected = document.works.find(work => work.id === document.selectedId);
  const update = (id: string, transform: (work: Work) => Work) => setDocument(current => ({ ...current, works: current.works.map(work => work.id === id ? transform(work) : work) }));
  const choose = (id: string) => { setDocument(current => ({ ...current, selectedId: id })); setTab('summary'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const back = () => setDocument(current => ({ ...current, selectedId: '' }));

  if (!ready) return <main className="works-studio" role="status">Abriendo tus obras…</main>;
  return <main className="works-studio">
    <header className="works-header"><div><span className="works-eyebrow">GESTOR DE OBRAS</span><h1>Obras en movimiento.</h1><p>Planifica, registra el avance y controla cada obra desde un solo lugar.</p></div><div className="works-header-actions"><span className="works-save">{saved ? <><Check size={14}/> Guardado</> : 'Guardando…'}</span>{selected && <button onClick={back}><ArrowLeft size={16}/> Todas las obras</button>}<button className="works-primary" onClick={() => setCreating(true)}><Plus size={16}/> Nueva obra</button></div></header>

    {notice && <p className="works-notice" role="status">{notice}</p>}
    {creating && <NewWork onCancel={() => setCreating(false)} onCreate={work => { setDocument(current => ({ ...current, selectedId: work.id, works: [...current.works, work] })); setCreating(false); setTab('summary'); }}/>} 
    {!selected && <Portfolio document={document} view={rootView} onView={setRootView} onChoose={choose} onCreate={() => setCreating(true)}/>} 
    {selected && <WorkDetail work={selected} tab={tab} onTab={setTab} onChange={transform => update(selected.id, transform)} onDelete={() => { if (window.confirm(`¿Eliminar la obra “${selected.name}”? Esta acción no se puede deshacer.`)) setDocument(current => ({ ...current, selectedId: '', works: current.works.filter(work => work.id !== selected.id) })); }} onNotice={setNotice}/>} 
  </main>;
}

function NewWork({ onCancel, onCreate }: { onCancel: () => void; onCreate: (work: Work) => void }) {
  const [form, setForm] = useState({ name: '', client: '', location: '', start: today(), end: '', budget: 0 });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.name.trim()) return; onCreate(newWork({ ...form, name: form.name.trim(), budget: clamp(form.budget) })); };
  return <section className="works-new"><div><span className="works-eyebrow">NUEVA OBRA</span><h2>Crea la ficha base</h2><p>Luego podrás traer el presupuesto de Costos o cargar el cronograma desde Excel.</p></div><form onSubmit={submit}><Field label="Nombre de la obra"><input autoFocus required value={form.name} onChange={event => setForm({...form,name:event.target.value})}/></Field><Field label="Cliente"><input value={form.client} onChange={event => setForm({...form,client:event.target.value})}/></Field><Field label="Ubicación"><input value={form.location} onChange={event => setForm({...form,location:event.target.value})}/></Field><Field label="Inicio"><input type="date" required value={form.start} onChange={event => setForm({...form,start:event.target.value})}/></Field><Field label="Fin previsto"><input type="date" value={form.end} min={form.start} onChange={event => setForm({...form,end:event.target.value})}/></Field><Field label="Valor contratado"><input type="number" min="0" step="0.01" value={form.budget} onChange={event => setForm({...form,budget:number(event.target.value)})}/></Field><div className="works-form-actions"><button type="button" onClick={onCancel}>Cancelar</button><button className="works-primary" type="submit">Crear obra</button></div></form></section>;
}

function Portfolio({ document, view, onView, onChoose, onCreate }: { document: WorksDocument; view: 'portfolio'|'timeline'; onView: (value:'portfolio'|'timeline')=>void; onChoose:(id:string)=>void; onCreate:()=>void }) {
  const active = document.works.filter(work => work.status === 'active').length;
  const attention = document.works.filter(work => work.tasks.some(task => taskStatus(task) === 'late') || work.risks.some(risk => risk.status !== 'closed' && riskScore(risk) >= 15)).length;
  const completed = document.works.filter(work => work.status === 'completed').length;
  return <>
    <nav className="works-root-tabs"><button aria-pressed={view==='portfolio'} onClick={()=>onView('portfolio')}>Todas las obras</button><button aria-pressed={view==='timeline'} onClick={()=>onView('timeline')}>Cronograma general</button></nav>
    <section className="works-kpis"><article><span>Obras registradas</span><strong>{document.works.length}</strong></article><article><span>En ejecución</span><strong>{active}</strong></article><article className={attention?'is-warning':''}><span>Requieren atención</span><strong>{attention}</strong></article><article><span>Completadas</span><strong>{completed}</strong></article></section>
    {!document.works.length ? <section className="works-empty"><HardHat size={46}/><h2>De la planificación al avance real.</h2><p>Crea una obra, importa su cronograma y empieza a documentar el proceso.</p><button className="works-primary" onClick={onCreate}><Plus size={16}/> Crear la primera obra</button></section> : view === 'portfolio' ? <section className="works-grid">{document.works.map(work => { const progress=percentage(work); const late=work.tasks.filter(task=>taskStatus(task)==='late').length; const financial=finances(work); return <button className="works-card" key={work.id} onClick={()=>onChoose(work.id)}><div className="works-card-top"><span className={`works-status is-${work.status}`}>{statusLabel[work.status]}</span><span>{work.location||'Sin ubicación'}</span></div><h2>{work.name}</h2><p>{work.client||'Cliente por definir'}</p><div className="works-progress"><span style={{width:`${progress}%`}}/></div><div className="works-card-stats"><span><b>{progress}%</b> avance</span><span className={late?'is-late':''}><b>{late}</b> atrasos</span><span><b>{money(financial.expenses)}</b> ejecutado</span></div></button>;})}</section> : <GeneralTimeline works={document.works} onChoose={onChoose}/>} 
  </>;
}

function GeneralTimeline({ works, onChoose }: { works: Work[]; onChoose:(id:string)=>void }) {
  const dated = works.filter(work=>work.start&&work.end);
  if (!dated.length) return <p className="works-empty">Añade fechas de inicio y fin para ver el cronograma consolidado.</p>;
  const min=Math.min(...dated.map(work=>Date.parse(work.start))); const max=Math.max(...dated.map(work=>Date.parse(work.end))); const span=Math.max(86_400_000,max-min);
  return <section className="works-panel"><div className="works-section-head"><div><span className="works-eyebrow">PORTAFOLIO</span><h2>Cronograma general</h2></div><p>La barra completa representa el plazo; el color intenso muestra el avance.</p></div><div className="works-gantt works-general-gantt">{dated.map(work=>{const left=(Date.parse(work.start)-min)/span*100;const width=Math.max(2,(Date.parse(work.end)-Date.parse(work.start))/span*100);const progress=percentage(work);return <button key={work.id} onClick={()=>onChoose(work.id)}><strong>{work.name}</strong><span className="works-gantt-track"><span className="works-gantt-range" style={{left:`${left}%`,width:`${width}%`}}><i style={{width:`${progress}%`}}/></span></span><small>{progress}%</small></button>;})}</div></section>;
}

function WorkDetail({ work, tab, onTab, onChange, onDelete, onNotice }: { work: Work; tab: DetailTab; onTab:(tab:DetailTab)=>void; onChange:(transform:(work:Work)=>Work)=>void; onDelete:()=>void; onNotice:(text:string)=>void }) {
  const progress=percentage(work); const financial=finances(work); const late=work.tasks.filter(task=>taskStatus(task)==='late').length;
  const edit=(patch:Partial<Work>)=>onChange(current=>({...current,...patch}));
  return <>
    <section className="works-project-head"><div><span className={`works-status is-${work.status}`}>{statusLabel[work.status]}</span><h2>{work.name}</h2><p>{[work.client,work.location].filter(Boolean).join(' · ')||'Completa los datos de la obra'}</p></div><div className="works-project-numbers"><span><b>{progress}%</b> avance</span><span className={late?'is-late':''}><b>{late}</b> atrasos</span><span><b>{money(financial.expenses)}</b> ejecutado</span></div></section>
    <nav className="works-tabs" aria-label="Secciones de la obra">{([['summary','Resumen'],['schedule','Cronograma'],['log','Bitácora'],['team','Equipo'],['risks','Riesgos'],['money','Economía']] as [DetailTab,string][]).map(([value,label])=><button key={value} aria-pressed={tab===value} onClick={()=>onTab(value)}>{label}</button>)}</nav>
    {tab==='summary'&&<Summary work={work} edit={edit} onTab={onTab}/>} 
    {tab==='schedule'&&<Schedule work={work} onChange={onChange} onNotice={onNotice}/>} 
    {tab==='log'&&<Logbook work={work} onChange={onChange} onNotice={onNotice}/>} 
    {tab==='team'&&<Team work={work} onChange={onChange}/>} 
    {tab==='risks'&&<Risks work={work} onChange={onChange}/>} 
    {tab==='money'&&<Economy work={work} onChange={onChange} onNotice={onNotice}/>} 
    <details className="works-danger"><summary>Administrar obra</summary><button onClick={onDelete}><Trash2 size={15}/> Eliminar esta obra</button></details>
  </>;
}

function Summary({ work, edit, onTab }: { work: Work; edit:(patch:Partial<Work>)=>void; onTab:(tab:DetailTab)=>void }) {
  const progress=percentage(work); const financial=finances(work); const openRisks=work.risks.filter(risk=>risk.status!=='closed').sort((a,b)=>riskScore(b)-riskScore(a));
  return <div className="works-summary-layout"><section className="works-panel"><div className="works-section-head"><div><span className="works-eyebrow">FICHA DE OBRA</span><h2>Datos generales</h2></div></div><div className="works-form-grid"><Field label="Nombre"><input value={work.name} onChange={event=>edit({name:event.target.value})}/></Field><Field label="Cliente"><input value={work.client} onChange={event=>edit({client:event.target.value})}/></Field><Field label="Ubicación"><input value={work.location} onChange={event=>edit({location:event.target.value})}/></Field><Field label="Estado"><select value={work.status} onChange={event=>edit({status:event.target.value as Work['status']})}><option value="planning">Planificación</option><option value="active">En ejecución</option><option value="paused">Pausada</option><option value="completed">Completada</option></select></Field><Field label="Inicio"><input type="date" value={work.start} onChange={event=>edit({start:event.target.value})}/></Field><Field label="Fin previsto"><input type="date" value={work.end} onChange={event=>edit({end:event.target.value})}/></Field><Field label="Descripción y alcance"><textarea rows={4} value={work.description} onChange={event=>edit({description:event.target.value})}/></Field></div></section><aside className="works-side-stack"><article className="works-panel works-progress-ring"><div style={{'--progress':`${progress*3.6}deg`} as React.CSSProperties}><strong>{progress}%</strong><span>avance ponderado</span></div><button onClick={()=>onTab('schedule')}>Revisar cronograma</button></article><article className="works-panel works-quick"><h3>Control actual</h3><p><span>Presupuesto</span><b>{money(work.budget)}</b></p><p><span>Ejecutado</span><b>{money(financial.expenses)}</b></p><p><span>Por cobrar</span><b>{money(financial.pendingPayment)}</b></p><p><span>Riesgos abiertos</span><b>{openRisks.length}</b></p></article></aside><section className="works-panel works-wide"><div className="works-section-head"><div><span className="works-eyebrow">PRÓXIMO PASO</span><h2>Lo que requiere atención</h2></div></div><div className="works-attention"><button onClick={()=>onTab('schedule')}><CalendarDays/><b>{work.tasks.filter(task=>taskStatus(task)==='late').length} actividades atrasadas</b><span>Reprograma o actualiza su avance</span></button><button onClick={()=>onTab('risks')}><ShieldAlert/><b>{openRisks.filter(risk=>riskScore(risk)>=8).length} riesgos altos</b><span>Define responsables y respuestas</span></button><button onClick={()=>onTab('log')}><ClipboardList/><b>{work.logs.length} registros</b><span>Documenta el avance de hoy</span></button></div></section></div>;
}

function Schedule({ work, onChange, onNotice }: { work: Work; onChange:(transform:(work:Work)=>Work)=>void; onNotice:(text:string)=>void }) {
  const blank = { name:'',phase:'General',responsible:'',start:work.start||today(),end:work.start||today(),progress:0,notes:'' };
  const [form,setForm]=useState(blank); const [showForm,setShowForm]=useState(false);
  const phases=[...new Set(work.tasks.map(task=>task.phase||'General'))];
  const range=useMemo(()=>{const dated=work.tasks.filter(task=>task.start&&task.end);if(!dated.length)return null;const min=Math.min(...dated.map(task=>Date.parse(task.start)));const max=Math.max(...dated.map(task=>Date.parse(task.end)));return{min,span:Math.max(86_400_000,max-min)};},[work.tasks]);
  const add=(event:FormEvent)=>{event.preventDefault(); if(!form.name.trim())return;onChange(current=>({...current,tasks:[...current.tasks,{...form,id:uid(),progress:clamp(form.progress,100)}]}));setForm(blank);setShowForm(false);};
  const changeTask=(id:string,patch:Partial<WorkTask>)=>onChange(current=>({...current,tasks:current.tasks.map(task=>task.id===id?{...task,...patch}:task)}));
  const upload=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const tasks=await importSchedule(file);onChange(current=>({...current,tasks:[...current.tasks,...tasks]}));onNotice(`${tasks.length} actividades importadas desde ${file.name}.`);}catch(error){onNotice(error instanceof Error?error.message:'No se pudo leer el cronograma.');}};
  return <section className="works-panel"><div className="works-section-head"><div><span className="works-eyebrow">CRONOGRAMA</span><h2>Plan frente a avance real</h2><p>Las actividades atrasadas se detectan automáticamente.</p></div><div className="works-inline-actions"><button onClick={()=>void downloadScheduleTemplate()}><Download size={15}/> Formato Excel</button><label><Upload size={15}/> Importar cronograma<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event=>void upload(event)}/></label><button className="works-primary" onClick={()=>setShowForm(!showForm)}><Plus size={15}/> Actividad</button></div></div>
    {showForm&&<form className="works-inline-form" onSubmit={add}><Field label="Actividad"><input required value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></Field><Field label="Fase"><input list="work-phases" value={form.phase} onChange={event=>setForm({...form,phase:event.target.value})}/><datalist id="work-phases">{phases.map(phase=><option key={phase} value={phase}/>)}</datalist></Field><Field label="Responsable"><input list="work-team" value={form.responsible} onChange={event=>setForm({...form,responsible:event.target.value})}/><datalist id="work-team">{work.team.map(person=><option key={person.id} value={person.name}/>)}</datalist></Field><Field label="Inicio"><input type="date" required value={form.start} onChange={event=>setForm({...form,start:event.target.value})}/></Field><Field label="Fin"><input type="date" required min={form.start} value={form.end} onChange={event=>setForm({...form,end:event.target.value})}/></Field><Field label="Avance %"><input type="number" min="0" max="100" value={form.progress} onChange={event=>setForm({...form,progress:number(event.target.value)})}/></Field><button className="works-primary" type="submit">Añadir</button></form>}
    {!work.tasks.length?<p className="works-empty">Añade una actividad o importa tu cronograma de Excel.</p>:<div className="works-task-table"><div className="works-task-head"><span>Actividad</span><span>Responsable</span><span>Fechas</span><span>Avance</span><span>Estado</span><span/></div>{work.tasks.map(task=>{const status=taskStatus(task);const left=range?(Date.parse(task.start)-range.min)/range.span*100:0;const width=range?Math.max(2,(Date.parse(task.end)-Date.parse(task.start))/range.span*100):100;return <Fragment key={task.id}><div className="works-task-row"><div><input aria-label="Actividad" value={task.name} onChange={event=>changeTask(task.id,{name:event.target.value})}/><small>{task.phase||'General'}</small></div><input aria-label="Responsable" list="work-team" value={task.responsible} onChange={event=>changeTask(task.id,{responsible:event.target.value})}/><div className="works-task-dates"><input aria-label="Inicio" type="date" value={task.start} onChange={event=>changeTask(task.id,{start:event.target.value})}/><input aria-label="Fin" type="date" value={task.end} onChange={event=>changeTask(task.id,{end:event.target.value})}/></div><input aria-label="Avance" type="number" min="0" max="100" value={task.progress} onChange={event=>changeTask(task.id,{progress:clamp(event.target.valueAsNumber,100)})}/><span className={`works-task-status is-${status}`}>{taskLabel[status]}</span><button aria-label={`Eliminar ${task.name}`} onClick={()=>onChange(current=>({...current,tasks:current.tasks.filter(row=>row.id!==task.id)}))}><Trash2 size={15}/></button></div><div className="works-task-gantt"><span style={{left:`${left}%`,width:`${width}%`}}><i style={{width:`${task.progress}%`}}/></span></div></Fragment>;})}</div>}
  </section>;
}

function Logbook({ work, onChange, onNotice }: { work: Work; onChange:(transform:(work:Work)=>Work)=>void; onNotice:(text:string)=>void }) {
  const [form,setForm]=useState<Omit<WorkLog,'id'>>({date:today(),title:'',note:'',taskId:'',progress:undefined,image:undefined}); const [loading,setLoading]=useState(false);
  const add=(event:FormEvent)=>{event.preventDefault();if(!form.title.trim())return;onChange(current=>{const tasks=form.taskId&&form.progress!==undefined?current.tasks.map(task=>task.id===form.taskId?{...task,progress:clamp(form.progress||0,100)}:task):current.tasks;return{...current,tasks,logs:[{...form,id:uid()},...current.logs]};});setForm({date:today(),title:'',note:'',taskId:'',progress:undefined,image:undefined});};
  const image=async(event:ChangeEvent<HTMLInputElement>)=>{setLoading(true);try{const value=await evidence(event.target.files?.[0]);setForm(current=>({...current,image:value}));}catch(error){onNotice(error instanceof Error?error.message:'No se pudo abrir la imagen.');}finally{setLoading(false);event.target.value='';}};
  return <div className="works-log-layout"><section className="works-panel"><div className="works-section-head"><div><span className="works-eyebrow">BITÁCORA</span><h2>Documenta cada avance</h2></div></div><form className="works-log-form" onSubmit={add}><Field label="Fecha"><input type="date" value={form.date} onChange={event=>setForm({...form,date:event.target.value})}/></Field><Field label="Título"><input required placeholder="Ej. Fundición de contrapiso" value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></Field><Field label="Actividad relacionada"><select value={form.taskId} onChange={event=>setForm({...form,taskId:event.target.value,progress:event.target.value?form.progress:undefined})}><option value="">Sin actividad relacionada</option>{work.tasks.map(task=><option key={task.id} value={task.id}>{task.name}</option>)}</select></Field>{form.taskId&&<Field label="Actualizar avance %"><input type="number" min="0" max="100" value={form.progress??''} onChange={event=>setForm({...form,progress:event.target.value===''?undefined:clamp(event.target.valueAsNumber,100)})}/></Field>}<Field label="Detalle"><textarea rows={5} value={form.note} onChange={event=>setForm({...form,note:event.target.value})}/></Field><label className="works-evidence"><ImagePlus size={18}/>{loading?'Procesando imagen…':form.image?'Cambiar evidencia':'Adjuntar evidencia'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void image(event)}/></label>{form.image&&<img className="works-evidence-preview" src={form.image} alt="Evidencia por guardar"/>}<button className="works-primary" type="submit">Guardar registro</button></form></section><section className="works-panel works-log-list"><h2>Historial</h2>{!work.logs.length?<p className="works-empty">Todavía no hay avances registrados.</p>:work.logs.map(log=><article key={log.id}>{log.image&&<img src={log.image} alt="Evidencia de obra"/>}<div><time>{new Date(`${log.date}T12:00:00`).toLocaleDateString('es-EC')}</time><h3>{log.title}</h3><p>{log.note||'Sin observaciones.'}</p>{log.taskId&&<small>{work.tasks.find(task=>task.id===log.taskId)?.name}{log.progress!==undefined?` · avance actualizado a ${log.progress}%`:''}</small>}<button onClick={()=>onChange(current=>({...current,logs:current.logs.filter(row=>row.id!==log.id)}))}><Trash2 size={14}/> Eliminar</button></div></article>)}</section></div>;
}

function Team({ work, onChange }: { work: Work; onChange:(transform:(work:Work)=>Work)=>void }) {
  const [form,setForm]=useState({name:'',role:'',email:'',phone:''}); const add=(event:FormEvent)=>{event.preventDefault();if(!form.name.trim())return;onChange(current=>({...current,team:[...current.team,{...form,id:uid()}]}));setForm({name:'',role:'',email:'',phone:''});};
  return <section className="works-panel"><div className="works-section-head"><div><span className="works-eyebrow">RESPONSABILIDADES</span><h2>Equipo de la obra</h2><p>Cada actividad puede asignarse a una persona de esta lista.</p></div></div><form className="works-inline-form" onSubmit={add}><Field label="Nombre"><input required value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></Field><Field label="Rol"><input placeholder="Residente, fiscalizador…" value={form.role} onChange={event=>setForm({...form,role:event.target.value})}/></Field><Field label="Correo"><input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></Field><Field label="Teléfono"><input value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></Field><button className="works-primary" type="submit">Añadir</button></form><div className="works-people">{work.team.map(person=><article key={person.id}><span>{person.name.slice(0,1).toUpperCase()}</span><div><h3>{person.name}</h3><p>{person.role||'Rol por definir'}</p><small>{[person.email,person.phone].filter(Boolean).join(' · ')}</small></div><button onClick={()=>onChange(current=>({...current,team:current.team.filter(row=>row.id!==person.id),tasks:current.tasks.map(task=>task.responsible===person.name?{...task,responsible:''}:task)}))}><Trash2 size={15}/></button></article>)}</div>{!work.team.length&&<p className="works-empty">Añade al equipo para asignar responsables en el cronograma.</p>}</section>;
}

function Risks({ work, onChange }: { work: Work; onChange:(transform:(work:Work)=>Work)=>void }) {
  const blank:Omit<WorkRisk,'id'>={title:'',category:'Técnico',probability:3,impact:3,owner:'',response:'',status:'open'};const[form,setForm]=useState(blank);const add=(event:FormEvent)=>{event.preventDefault();if(!form.title.trim())return;onChange(current=>({...current,risks:[...current.risks,{...form,id:uid()}]}));setForm(blank);};
  return <section className="works-panel"><div className="works-section-head"><div><span className="works-eyebrow">MATRIZ SIMPLE</span><h2>Riesgos de obra</h2><p>Prioriza por probabilidad × impacto y define una respuesta concreta.</p></div></div><form className="works-inline-form works-risk-form" onSubmit={add}><Field label="Riesgo"><input required value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></Field><Field label="Categoría"><select value={form.category} onChange={event=>setForm({...form,category:event.target.value})}><option>Técnico</option><option>Plazo</option><option>Costo</option><option>Seguridad</option><option>Proveedor</option><option>Cliente</option></select></Field><Field label="Probabilidad 1–5"><input type="number" min="1" max="5" value={form.probability} onChange={event=>setForm({...form,probability:clamp(event.target.valueAsNumber,5)})}/></Field><Field label="Impacto 1–5"><input type="number" min="1" max="5" value={form.impact} onChange={event=>setForm({...form,impact:clamp(event.target.valueAsNumber,5)})}/></Field><Field label="Responsable"><input list="risk-team" value={form.owner} onChange={event=>setForm({...form,owner:event.target.value})}/><datalist id="risk-team">{work.team.map(person=><option key={person.id} value={person.name}/>)}</datalist></Field><Field label="Respuesta"><input value={form.response} onChange={event=>setForm({...form,response:event.target.value})}/></Field><button className="works-primary" type="submit">Añadir riesgo</button></form><div className="works-risks">{[...work.risks].sort((a,b)=>riskScore(b)-riskScore(a)).map(risk=>{const score=riskScore(risk);return <article key={risk.id} className={`is-${riskLevel(score)}`}><span className="works-risk-score">{score}</span><div><small>{risk.category} · {riskLevel(score).toUpperCase()}</small><h3>{risk.title}</h3><p>{risk.response||'Sin respuesta definida'} · {risk.owner||'Sin responsable'}</p></div><select aria-label={`Estado de ${risk.title}`} value={risk.status} onChange={event=>onChange(current=>({...current,risks:current.risks.map(row=>row.id===risk.id?{...row,status:event.target.value as WorkRisk['status']}:row)}))}><option value="open">Abierto</option><option value="controlled">Controlado</option><option value="closed">Cerrado</option></select><button onClick={()=>onChange(current=>({...current,risks:current.risks.filter(row=>row.id!==risk.id)}))}><Trash2 size={15}/></button></article>;})}</div>{!work.risks.length&&<p className="works-empty">No hay riesgos registrados.</p>}</section>;
}

function Economy({ work, onChange, onNotice }: { work: Work; onChange:(transform:(work:Work)=>Work)=>void; onNotice:(text:string)=>void }) {
  const blank:Omit<WorkMovement,'id'>={date:today(),type:'expense',category:'Materiales',description:'',amount:0};const[form,setForm]=useState(blank);const f=finances(work);
  const add=(event:FormEvent)=>{event.preventDefault();if(!form.description.trim()||!form.amount)return;onChange(current=>({...current,movements:[{...form,id:uid()},...current.movements]}));setForm(blank);};
  const importBudget=async()=>{try{const value=await readDocument('arquirender-budget-v1');if(!validBudget(value)){onNotice('No encontramos un presupuesto válido en Costos.');return;}const total=totals(value).total;onChange(current=>({...current,budget:total}));onNotice(`Valor contratado actualizado desde Costos: ${money(total)}.`);}catch{onNotice('No se pudo leer el presupuesto de Costos.');}};
  const byCategory=useMemo(()=>{const map=new Map<string,number>();work.movements.filter(row=>row.type==='expense').forEach(row=>map.set(row.category,(map.get(row.category)||0)+row.amount));return [...map.entries()].sort((a,b)=>b[1]-a[1]);},[work.movements]);
  return <><section className="works-money-kpis"><article><span>Valor contratado</span><strong>{money(work.budget)}</strong><button onClick={()=>void importBudget()}>Traer desde Costos</button></article><article><span>Ingresado</span><strong>{money(f.payments)}</strong><small>Por cobrar {money(f.pendingPayment)}</small></article><article><span>Ejecutado</span><strong>{money(f.expenses)}</strong><small>Disponible {money(f.budgetBalance)}</small></article><article className={f.cashBalance<0?'is-warning':''}><span>Flujo disponible</span><strong>{money(f.cashBalance)}</strong><small>Cobros menos egresos</small></article></section><div className="works-money-layout"><section className="works-panel"><div className="works-section-head"><div><span className="works-eyebrow">MOVIMIENTOS</span><h2>Cobros y egresos</h2></div></div><form className="works-inline-form" onSubmit={add}><Field label="Fecha"><input type="date" value={form.date} onChange={event=>setForm({...form,date:event.target.value})}/></Field><Field label="Tipo"><select value={form.type} onChange={event=>setForm({...form,type:event.target.value as WorkMovement['type']})}><option value="expense">Egreso</option><option value="payment">Cobro</option></select></Field><Field label="Categoría"><input value={form.category} onChange={event=>setForm({...form,category:event.target.value})}/></Field><Field label="Descripción"><input required value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></Field><Field label="Monto"><input required type="number" min="0" step="0.01" value={form.amount} onChange={event=>setForm({...form,amount:number(event.target.value)})}/></Field><button className="works-primary" type="submit">Registrar</button></form><div className="works-movements">{work.movements.map(row=><article key={row.id}><span className={`is-${row.type}`}>{row.type==='expense'?'Egreso':'Cobro'}</span><div><h3>{row.description}</h3><small>{row.date} · {row.category}</small></div><b>{row.type==='expense'?'-':'+'}{money(row.amount)}</b><button onClick={()=>onChange(current=>({...current,movements:current.movements.filter(item=>item.id!==row.id)}))}><Trash2 size={14}/></button></article>)}</div>{!work.movements.length&&<p className="works-empty">Registra el primer cobro o egreso.</p>}</section><aside className="works-panel"><h2>Egresos por categoría</h2>{byCategory.map(([category,amount])=><div className="works-cost-bar" key={category}><p><span>{category}</span><b>{money(amount)}</b></p><span><i style={{width:`${f.expenses?amount/f.expenses*100:0}%`}}/></span></div>)}{!byCategory.length&&<p className="works-empty">Aquí verás la distribución de los egresos.</p>}</aside></div></>;
}
